FROM registry.leju.com:5043/baseimages/php:5.6-fpm

MAINTAINER Jiashiwen "shiwen4@leju.com"

ADD ./envconfig /envconfig
RUN mkdir -p /search.leju.com

#Install php extention
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        php5-memcache \
    && docker-php-ext-install iconv mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-configure mysql \
    && docker-php-ext-install mysql \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install mbstring

# Install memcached
COPY memcached-2.2.0.tgz /tmp/memcached-2.2.0.tgz
RUN apt-get install -y libmemcached-dev zlib1g-dev libncurses5-dev
RUN tar -xf /tmp/memcached-2.2.0.tgz -C /usr/src/php/ext/
RUN rm /tmp/memcached-2.2.0.tgz
RUN docker-php-ext-install memcached-2.2.0

# Install memcache
COPY memcache-2.2.7.tgz /tmp/memcache-2.2.7.tgz
RUN tar -xf /tmp/memcache-2.2.7.tgz -C /usr/src/php/ext/
RUN rm /tmp/memcache-2.2.7.tgz
RUN docker-php-ext-install memcache-2.2.7

#Install redis module
RUN curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/2.2.7.tar.gz \
    && tar xfz /tmp/redis.tar.gz \
    && rm -r /tmp/redis.tar.gz \
    && mv phpredis-2.2.7 /usr/src/php/ext/redis \
    && docker-php-ext-install redis

#Install Nginx

ENV NGINX_VERSION 1.11.1-1~jessie

RUN apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 \
	&& echo "deb http://nginx.org/packages/mainline/debian/ jessie nginx" >> /etc/apt/sources.list \
	&& apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y \
						ca-certificates \
						nginx=${NGINX_VERSION} \
						nginx-module-xslt \
						nginx-module-geoip \
						nginx-module-image-filter \
						nginx-module-perl \
						nginx-module-njs \
						gettext-base \
	&& rm -rf /var/lib/apt/lists/*

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

VOLUME ["/var/cache/nginx"]

#Install Supervisor
RUN apt-get update && apt-get install -y openssh-server supervisor \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean
RUN mkdir -p /var/run/nginx /var/log/supervisor /var/run/php-fpm
COPY ./envconfig/supervisord/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 443 80 9000

CMD ["/usr/bin/supervisord","-c","/envconfig/supervisord/supervisord.conf"]
