#  search.leju.com local port:8000 9000;8001 9001;8002 9002;8003 9003

version: '2'

services:
  baike.leju.com-php5-fpm_00:
      image: app-php-fpm:7.1
      command: /envconfig/initphpfpm.sh
      #cpuset: 6-9
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./baike.leju.com:/project
        - ./runtimephpfpm/runtime_00:/envconfig
      network_mode: "host"
      container_name: app-php7-fpm_00

  search.leju.com-nginx:
      image: app-nginx:1.12
      command: /envconfig/initnginx.sh
      #cpuset: 4-5
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./baike.leju.com:/project
        - ./runtimenginx/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./runtimenginx:/envconfig
      network_mode: "host"
      container_name: app-nginx
  
