FROM php:5.6-fpm

MAINTAINER Jiashiwen "shiwen4@leju.com"

ADD ./envconfig /envconfig
RUN mkdir -p /project

#Install php extention
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        php5-memcache \
    && docker-php-ext-install iconv mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-configure mysql \
    && docker-php-ext-install mysql \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install mbstring

# Install memcached
RUN apt-get install -y libmemcached-dev zlib1g-dev libncurses5-dev
RUN pecl install memcached-2.2.0
RUN docker-php-ext-enable memcached
 
# Install memcache
RUN pecl install memcache-2.2.7
RUN docker-php-ext-enable memcache

#Install redis module
RUN pecl install redis-2.2.8
RUN docker-php-ext-enable redis 

#Install Xdebug
RUN pecl install xdebug 
RUN docker-php-ext-enable xdebug

#Install forp-PHP-profiler
RUN set -x \
  && curl -sSL -o /tmp/forp-PHP-profiler-1.1.0.tar.gz https://github.com/aterrien/forp/archive/1.1.0.tar.gz \
  && tar zxvf /tmp/forp-PHP-profiler-1.1.0.tar.gz -C /tmp/ \
  && cd /tmp/forp-PHP-profiler-1.1.0/ext/forp/ \
  && /usr/local/bin/phpize \
  && ./configure --with-php-config=/usr/local/bin/php-config \
  && make \
  && make install \
  && echo "extension=forp.so" > /usr/local/etc/php/conf.d/ext-forp.ini 

#Clean apt
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


EXPOSE 9000 19000

CMD ["php-fpm"]
