<?php
return array (
	'ALL' => array (
		'aa' => array (
			'l' => 'A',
			'en' => 'aa',
			'cn' => '阿拉善盟',
			'py' => 'alashanmeng',
		),
		'ab' => array (
			'l' => 'A',
			'en' => 'ab',
			'cn' => '阿坝',
			'py' => 'aba',
		),
		'af' => array (
			'l' => 'A',
			'en' => 'af',
			'cn' => '安福',
			'py' => 'anfu',
		),
		'ai' => array (
			'l' => 'A',
			'en' => 'ai',
			'cn' => '安庆',
			'py' => 'anqing',
		),
		'ak' => array (
			'l' => 'A',
			'en' => 'ak',
			'cn' => '安康',
			'py' => 'ankang',
		),
		'al' => array (
			'l' => 'A',
			'en' => 'al',
			'cn' => '阿里',
			'py' => 'ali',
		),
		'an' => array (
			'l' => 'A',
			'en' => 'an',
			'cn' => '安顺',
			'py' => 'anshun',
		),
		'anshan' => array (
			'l' => 'A',
			'en' => 'anshan',
			'cn' => '鞍山',
			'py' => 'anshan',
		),
		'ay' => array (
			'l' => 'A',
			'en' => 'ay',
			'cn' => '安阳',
			'py' => 'anyang',
		),
		'aj' => array (
			'l' => 'B',
			'en' => 'aj',
			'cn' => '宝鸡',
			'py' => 'baoji',
		),
		'baoding' => array (
			'l' => 'B',
			'en' => 'baoding',
			'cn' => '保定',
			'py' => 'baoding',
		),
		'bb' => array (
			'l' => 'B',
			'en' => 'bb',
			'cn' => '蚌埠',
			'py' => 'bengbu',
		),
		'bc' => array (
			'l' => 'B',
			'en' => 'bc',
			'cn' => '百色',
			'py' => 'baise',
		),
		'be' => array (
			'l' => 'B',
			'en' => 'be',
			'cn' => '毕节',
			'py' => 'bijie',
		),
		'beihai' => array (
			'l' => 'B',
			'en' => 'beihai',
			'cn' => '北海',
			'py' => 'beihai',
		),
		'bf' => array (
			'l' => 'B',
			'en' => 'bf',
			'cn' => '白城',
			'py' => 'baicheng',
		),
		'bj' => array (
			'l' => 'B',
			'en' => 'bj',
			'cn' => '北京',
			'py' => 'beijing',
		),
		'bk' => array (
			'l' => 'B',
			'en' => 'bk',
			'cn' => '白山',
			'py' => 'baishan',
		),
		'bn' => array (
			'l' => 'B',
			'en' => 'bn',
			'cn' => '滨州',
			'py' => 'binzhou',
		),
		'bo' => array (
			'l' => 'B',
			'en' => 'bo',
			'cn' => '亳州',
			'py' => 'bozhou',
		),
		'boao' => array (
			'l' => 'B',
			'en' => 'boao',
			'cn' => '博鳌',
			'py' => 'boao',
		),
		'bs' => array (
			'l' => 'B',
			'en' => 'bs',
			'cn' => '保山',
			'py' => 'baoshan',
		),
		'bt' => array (
			'l' => 'B',
			'en' => 'bt',
			'cn' => '包头',
			'py' => 'baotou',
		),
		'bx' => array (
			'l' => 'B',
			'en' => 'bx',
			'cn' => '本溪',
			'py' => 'benxi',
		),
		'bz' => array (
			'l' => 'B',
			'en' => 'bz',
			'cn' => '巴中',
			'py' => 'bazhong',
		),
		'ia' => array (
			'l' => 'B',
			'en' => 'ia',
			'cn' => '白银',
			'py' => 'baiyin',
		),
		'ne' => array (
			'l' => 'B',
			'en' => 'ne',
			'cn' => '巴彦淖尔',
			'py' => 'bayannaoer',
		),
		'ce' => array (
			'l' => 'C',
			'en' => 'ce',
			'cn' => '承德',
			'py' => 'chengde',
		),
		'cf' => array (
			'l' => 'C',
			'en' => 'cf',
			'cn' => '赤峰',
			'py' => 'chifeng',
		),
		'cg' => array (
			'l' => 'C',
			'en' => 'cg',
			'cn' => '昌都',
			'py' => 'changdu',
		),
		'changde' => array (
			'l' => 'C',
			'en' => 'changde',
			'cn' => '常德',
			'py' => 'changde',
		),
		'changshu' => array (
			'l' => 'C',
			'en' => 'changshu',
			'cn' => '常熟',
			'py' => 'changshu',
		),
		'chenzhou' => array (
			'l' => 'C',
			'en' => 'chenzhou',
			'cn' => '郴州',
			'py' => 'chenzhou',
		),
		'ci' => array (
			'l' => 'C',
			'en' => 'ci',
			'cn' => '长治',
			'py' => 'changzhi',
		),
		'cj' => array (
			'l' => 'C',
			'en' => 'cj',
			'cn' => '滁州',
			'py' => 'chuzhou',
		),
		'cl' => array (
			'l' => 'C',
			'en' => 'cl',
			'cn' => '巢湖',
			'py' => 'chaohu',
		),
		'cm' => array (
			'l' => 'C',
			'en' => 'cm',
			'cn' => '长垣',
			'py' => 'changyuan',
		),
		'cn' => array (
			'l' => 'C',
			'en' => 'cn',
			'cn' => '昌图',
			'py' => 'changtu',
		),
		'co' => array (
			'l' => 'C',
			'en' => 'co',
			'cn' => '沧州',
			'py' => 'cangzhou',
		),
		'cq' => array (
			'l' => 'C',
			'en' => 'cq',
			'cn' => '重庆',
			'py' => 'chongqing',
		),
		'cs' => array (
			'l' => 'C',
			'en' => 'cs',
			'cn' => '长沙',
			'py' => 'changsha',
		),
		'ct' => array (
			'l' => 'C',
			'en' => 'ct',
			'cn' => '崇左',
			'py' => 'chongzuo',
		),
		'cu' => array (
			'l' => 'C',
			'en' => 'cu',
			'cn' => '潮州',
			'py' => 'chaozhou',
		),
		'cx' => array (
			'l' => 'C',
			'en' => 'cx',
			'cn' => '楚雄',
			'py' => 'chuxiong',
		),
		'cy' => array (
			'l' => 'C',
			'en' => 'cy',
			'cn' => '朝阳',
			'py' => 'chaoyang',
		),
		'cz' => array (
			'l' => 'C',
			'en' => 'cz',
			'cn' => '常州',
			'py' => 'changzhou',
		),
		'dj' => array (
			'l' => 'C',
			'en' => 'dj',
			'cn' => '昌吉',
			'py' => 'changji',
		),
		'iu' => array (
			'l' => 'C',
			'en' => 'iu',
			'cn' => '池州',
			'py' => 'chizhou',
		),
		'jl' => array (
			'l' => 'C',
			'en' => 'jl',
			'cn' => '长春',
			'py' => 'changchun',
		),
		'sc' => array (
			'l' => 'C',
			'en' => 'sc',
			'cn' => '成都',
			'py' => 'chengdou',
		),
		'da' => array (
			'l' => 'D',
			'en' => 'da',
			'cn' => '大理',
			'py' => 'dali',
		),
		'daqing' => array (
			'l' => 'D',
			'en' => 'daqing',
			'cn' => '大庆',
			'py' => 'daqing',
		),
		'dazhou' => array (
			'l' => 'D',
			'en' => 'dazhou',
			'cn' => '达州',
			'py' => 'dazhou',
		),
		'dc' => array (
			'l' => 'D',
			'en' => 'dc',
			'cn' => '定州',
			'py' => 'dingzhou',
		),
		'dd' => array (
			'l' => 'D',
			'en' => 'dd',
			'cn' => '丹东',
			'py' => 'dandong',
		),
		'deyang' => array (
			'l' => 'D',
			'en' => 'deyang',
			'cn' => '德阳',
			'py' => 'deyang',
		),
		'dg' => array (
			'l' => 'D',
			'en' => 'dg',
			'cn' => '东莞',
			'py' => 'dongguan',
		),
		'dh' => array (
			'l' => 'D',
			'en' => 'dh',
			'cn' => '德宏',
			'py' => 'dehong',
		),
		'di' => array (
			'l' => 'D',
			'en' => 'di',
			'cn' => '迪庆',
			'py' => 'diqing',
		),
		'dl' => array (
			'l' => 'D',
			'en' => 'dl',
			'cn' => '大连',
			'py' => 'dalian',
		),
		'do' => array (
			'l' => 'D',
			'en' => 'do',
			'cn' => '邓州',
			'py' => 'dengzhou',
		),
		'dt' => array (
			'l' => 'D',
			'en' => 'dt',
			'cn' => '大同',
			'py' => 'datong',
		),
		'du' => array (
			'l' => 'D',
			'en' => 'du',
			'cn' => '德州',
			'py' => 'dezhou',
		),
		'dx' => array (
			'l' => 'D',
			'en' => 'dx',
			'cn' => '定西',
			'py' => 'dingxi',
		),
		'dy' => array (
			'l' => 'D',
			'en' => 'dy',
			'cn' => '东营',
			'py' => 'dongying',
		),
		'ig' => array (
			'l' => 'D',
			'en' => 'ig',
			'cn' => '大兴安岭',
			'py' => 'daxinganling',
		),
		'eeds' => array (
			'l' => 'E',
			'en' => 'eeds',
			'cn' => '鄂尔多斯',
			'py' => 'eerduosi',
		),
		'es' => array (
			'l' => 'E',
			'en' => 'es',
			'cn' => '恩施',
			'py' => 'enshi',
		),
		'ez' => array (
			'l' => 'E',
			'en' => 'ez',
			'cn' => '鄂州',
			'py' => 'ezhou',
		),
		'fa' => array (
			'l' => 'F',
			'en' => 'fa',
			'cn' => '抚顺',
			'py' => 'fushun',
		),
		'fcg' => array (
			'l' => 'F',
			'en' => 'fcg',
			'cn' => '防城港',
			'py' => 'fangchenggang',
		),
		'fe' => array (
			'l' => 'F',
			'en' => 'fe',
			'cn' => '丰城',
			'py' => 'fengcheng',
		),
		'fg' => array (
			'l' => 'F',
			'en' => 'fg',
			'cn' => '府谷',
			'py' => 'fugu',
		),
		'fj' => array (
			'l' => 'F',
			'en' => 'fj',
			'cn' => '福州',
			'py' => 'fuzhou',
		),
		'fo' => array (
			'l' => 'F',
			'en' => 'fo',
			'cn' => '抚州',
			'py' => 'fuzhou',
		),
		'fq' => array (
			'l' => 'F',
			'en' => 'fq',
			'cn' => '福泉',
			'py' => 'fuquan',
		),
		'fs' => array (
			'l' => 'F',
			'en' => 'fs',
			'cn' => '佛山',
			'py' => 'foshan',
		),
		'fu' => array (
			'l' => 'F',
			'en' => 'fu',
			'cn' => '抚远',
			'py' => 'fuyuan',
		),
		'fx' => array (
			'l' => 'F',
			'en' => 'fx',
			'cn' => '阜新',
			'py' => 'fuxin',
		),
		'fy' => array (
			'l' => 'F',
			'en' => 'fy',
			'cn' => '阜阳',
			'py' => 'fuyang',
		),
		'ga' => array (
			'l' => 'G',
			'en' => 'ga',
			'cn' => '广安',
			'py' => 'guangan',
		),
		'ganzhou' => array (
			'l' => 'G',
			'en' => 'ganzhou',
			'cn' => '赣州',
			'py' => 'ganzhou',
		),
		'gb' => array (
			'l' => 'G',
			'en' => 'gb',
			'cn' => '甘南',
			'py' => 'gannan',
		),
		'gc' => array (
			'l' => 'G',
			'en' => 'gc',
			'cn' => '固原',
			'py' => 'guyuan',
		),
		'gd' => array (
			'l' => 'G',
			'en' => 'gd',
			'cn' => '广德',
			'py' => 'guangde',
		),
		'gf' => array (
			'l' => 'G',
			'en' => 'gf',
			'cn' => '果洛',
			'py' => 'guoluo',
		),
		'gg' => array (
			'l' => 'G',
			'en' => 'gg',
			'cn' => '贵港',
			'py' => 'guigang',
		),
		'gi' => array (
			'l' => 'G',
			'en' => 'gi',
			'cn' => '广元',
			'py' => 'guangyuan',
		),
		'go' => array (
			'l' => 'G',
			'en' => 'go',
			'cn' => '巩义',
			'py' => 'gongyi',
		),
		'gq' => array (
			'l' => 'G',
			'en' => 'gq',
			'cn' => '共青城',
			'py' => 'gongqingcheng',
		),
		'gs' => array (
			'l' => 'G',
			'en' => 'gs',
			'cn' => '甘孜',
			'py' => 'ganzi',
		),
		'gu' => array (
			'l' => 'G',
			'en' => 'gu',
			'cn' => '固始',
			'py' => 'gushi',
		),
		'guilin' => array (
			'l' => 'G',
			'en' => 'guilin',
			'cn' => '桂林',
			'py' => 'guilin',
		),
		'guizhou' => array (
			'l' => 'G',
			'en' => 'guizhou',
			'cn' => '贵阳',
			'py' => 'guiyang',
		),
		'gz' => array (
			'l' => 'G',
			'en' => 'gz',
			'cn' => '广州',
			'py' => 'guangzhou',
		),
		'zl' => array (
			'l' => 'G',
			'en' => 'zl',
			'cn' => '公主岭',
			'py' => 'gongzhuling',
		),
		'az' => array (
			'l' => 'H',
			'en' => 'az',
			'cn' => '汉中',
			'py' => 'hanzhong',
		),
		'db' => array (
			'l' => 'H',
			'en' => 'db',
			'cn' => '海东',
			'py' => 'haidong',
		),
		'ea' => array (
			'l' => 'H',
			'en' => 'ea',
			'cn' => '海北',
			'py' => 'haibei',
		),
		'eg' => array (
			'l' => 'H',
			'en' => 'eg',
			'cn' => '鹤岗',
			'py' => 'hegang',
		),
		'eh' => array (
			'l' => 'H',
			'en' => 'eh',
			'cn' => '菏泽',
			'py' => 'heze',
		),
		'ei' => array (
			'l' => 'H',
			'en' => 'ei',
			'cn' => '黑河',
			'py' => 'heihe',
		),
		'er' => array (
			'l' => 'H',
			'en' => 'er',
			'cn' => '呼伦贝尔',
			'py' => 'hulunbeier',
		),
		'h' => array (
			'l' => 'H',
			'en' => 'h',
			'cn' => '哈尔滨',
			'py' => 'haerbin',
		),
		'han' => array (
			'l' => 'H',
			'en' => 'han',
			'cn' => '海口',
			'py' => 'haikou',
		),
		'handan' => array (
			'l' => 'H',
			'en' => 'handan',
			'cn' => '邯郸',
			'py' => 'handan',
		),
		'hangzhou' => array (
			'l' => 'H',
			'en' => 'hangzhou',
			'cn' => '杭州',
			'py' => 'hangzhou',
		),
		'hb' => array (
			'l' => 'H',
			'en' => 'hb',
			'cn' => '河源',
			'py' => 'heyuan',
		),
		'hc' => array (
			'l' => 'H',
			'en' => 'hc',
			'cn' => '淮南',
			'py' => 'huainan',
		),
		'he' => array (
			'l' => 'H',
			'en' => 'he',
			'cn' => '淮北',
			'py' => 'huaibei',
		),
		'hengyang' => array (
			'l' => 'H',
			'en' => 'hengyang',
			'cn' => '衡阳',
			'py' => 'hengyang',
		),
		'hf' => array (
			'l' => 'H',
			'en' => 'hf',
			'cn' => '合肥',
			'py' => 'hefei',
		),
		'hg' => array (
			'l' => 'H',
			'en' => 'hg',
			'cn' => '黄冈',
			'py' => 'huanggang',
		),
		'hh' => array (
			'l' => 'H',
			'en' => 'hh',
			'cn' => '怀化',
			'py' => 'huaihua',
		),
		'hhht' => array (
			'l' => 'H',
			'en' => 'hhht',
			'cn' => '呼和浩特',
			'py' => 'huhehaote',
		),
		'hj' => array (
			'l' => 'H',
			'en' => 'hj',
			'cn' => '淮安',
			'py' => 'huaian',
		),
		'hl' => array (
			'l' => 'H',
			'en' => 'hl',
			'cn' => '葫芦岛',
			'py' => 'huludao',
		),
		'hm' => array (
			'l' => 'H',
			'en' => 'hm',
			'cn' => '海门',
			'py' => 'haimen',
		),
		'ho' => array (
			'l' => 'H',
			'en' => 'ho',
			'cn' => '湖州',
			'py' => 'huzhou',
		),
		'hq' => array (
			'l' => 'H',
			'en' => 'hq',
			'cn' => '红河',
			'py' => 'honghe',
		),
		'hr' => array (
			'l' => 'H',
			'en' => 'hr',
			'cn' => '黄山',
			'py' => 'huangshan',
		),
		'hs' => array (
			'l' => 'H',
			'en' => 'hs',
			'cn' => '衡水',
			'py' => 'hengshui',
		),
		'ht' => array (
			'l' => 'H',
			'en' => 'ht',
			'cn' => '贺州',
			'py' => 'hezhou',
		),
		'huangshi' => array (
			'l' => 'H',
			'en' => 'huangshi',
			'cn' => '黄石',
			'py' => 'huangshi',
		),
		'huizhou' => array (
			'l' => 'H',
			'en' => 'huizhou',
			'cn' => '惠州',
			'py' => 'huizhou',
		),
		'hw' => array (
			'l' => 'H',
			'en' => 'hw',
			'cn' => '鹤壁',
			'py' => 'hebi',
		),
		'hx' => array (
			'l' => 'H',
			'en' => 'hx',
			'cn' => '河池',
			'py' => 'hechi',
		),
		'ih' => array (
			'l' => 'H',
			'en' => 'ih',
			'cn' => '海南藏族自治州',
			'py' => 'hainanzangzuzizhizho',
		),
		'nn' => array (
			'l' => 'H',
			'en' => 'nn',
			'cn' => '海宁',
			'py' => 'haining',
		),
		'nx' => array (
			'l' => 'H',
			'en' => 'nx',
			'cn' => '滑县',
			'py' => 'huaxian',
		),
		'od' => array (
			'l' => 'H',
			'en' => 'od',
			'cn' => '荷兰',
			'py' => 'helan',
		),
		'rh' => array (
			'l' => 'H',
			'en' => 'rh',
			'cn' => '怀仁',
			'py' => 'huairen',
		),
		'ua' => array (
			'l' => 'H',
			'en' => 'ua',
			'cn' => '黄南',
			'py' => 'huangnan',
		),
		'uu' => array (
			'l' => 'H',
			'en' => 'uu',
			'cn' => '韩城',
			'py' => 'hancheng',
		),
		'xk' => array (
			'l' => 'H',
			'en' => 'xk',
			'cn' => '海西',
			'py' => 'haixi',
		),
		'ag' => array (
			'l' => 'J',
			'en' => 'ag',
			'cn' => '金昌',
			'py' => 'jinchang',
		),
		'ja' => array (
			'l' => 'J',
			'en' => 'ja',
			'cn' => '锦州',
			'py' => 'jinzhou',
		),
		'jc' => array (
			'l' => 'J',
			'en' => 'jc',
			'cn' => '晋城',
			'py' => 'jincheng',
		),
		'jd' => array (
			'l' => 'J',
			'en' => 'jd',
			'cn' => '荆门',
			'py' => 'jingmen',
		),
		'je' => array (
			'l' => 'J',
			'en' => 'je',
			'cn' => '揭阳',
			'py' => 'jieyang',
		),
		'jf' => array (
			'l' => 'J',
			'en' => 'jf',
			'cn' => '吉安',
			'py' => 'jian',
		),
		'jh' => array (
			'l' => 'J',
			'en' => 'jh',
			'cn' => '金华',
			'py' => 'jinhua',
		),
		'ji' => array (
			'l' => 'J',
			'en' => 'ji',
			'cn' => '焦作',
			'py' => 'jiaozuo',
		),
		'jiangmen' => array (
			'l' => 'J',
			'en' => 'jiangmen',
			'cn' => '江门',
			'py' => 'jiangmen',
		),
		'jilin' => array (
			'l' => 'J',
			'en' => 'jilin',
			'cn' => '吉林',
			'py' => 'jilin',
		),
		'jingzhou' => array (
			'l' => 'J',
			'en' => 'jingzhou',
			'cn' => '荆州',
			'py' => 'jingzhou',
		),
		'jinzhong' => array (
			'l' => 'J',
			'en' => 'jinzhong',
			'cn' => '晋中',
			'py' => 'jinzhong',
		),
		'jiujiang' => array (
			'l' => 'J',
			'en' => 'jiujiang',
			'cn' => '九江',
			'py' => 'jiujiang',
		),
		'jk' => array (
			'l' => 'J',
			'en' => 'jk',
			'cn' => '金门',
			'py' => 'jinmen',
		),
		'jn' => array (
			'l' => 'J',
			'en' => 'jn',
			'cn' => '济宁',
			'py' => 'jining',
		),
		'jp' => array (
			'l' => 'J',
			'en' => 'jp',
			'cn' => '济源',
			'py' => 'jiyuan',
		),
		'jq' => array (
			'l' => 'J',
			'en' => 'jq',
			'cn' => '酒泉',
			'py' => 'jiuquan',
		),
		'js' => array (
			'l' => 'J',
			'en' => 'js',
			'cn' => '吉首',
			'py' => 'jishou',
		),
		'ju' => array (
			'l' => 'J',
			'en' => 'ju',
			'cn' => '嘉峪关',
			'py' => 'jiayuguan',
		),
		'jv' => array (
			'l' => 'J',
			'en' => 'jv',
			'cn' => '鸡西',
			'py' => 'jixi',
		),
		'jw' => array (
			'l' => 'J',
			'en' => 'jw',
			'cn' => '景德镇',
			'py' => 'jingdezhen',
		),
		'jx' => array (
			'l' => 'J',
			'en' => 'jx',
			'cn' => '嘉兴',
			'py' => 'jiaxing',
		),
		'jy' => array (
			'l' => 'J',
			'en' => 'jy',
			'cn' => '江阴',
			'py' => 'jiangyin',
		),
		'sd' => array (
			'l' => 'J',
			'en' => 'sd',
			'cn' => '济南',
			'py' => 'jinan',
		),
		'ss' => array (
			'l' => 'J',
			'en' => 'ss',
			'cn' => '佳木斯',
			'py' => 'jiamusi',
		),
		'ka' => array (
			'l' => 'K',
			'en' => 'ka',
			'cn' => '喀什',
			'py' => 'kashi',
		),
		'kf' => array (
			'l' => 'K',
			'en' => 'kf',
			'cn' => '开封',
			'py' => 'kaifeng',
		),
		'kl' => array (
			'l' => 'K',
			'en' => 'kl',
			'cn' => '凯里',
			'py' => 'kaili',
		),
		'ks' => array (
			'l' => 'K',
			'en' => 'ks',
			'cn' => '昆山',
			'py' => 'kunshan',
		),
		'yn' => array (
			'l' => 'K',
			'en' => 'yn',
			'cn' => '昆明',
			'py' => 'kunming',
		),
		'ac' => array (
			'l' => 'L',
			'en' => 'ac',
			'cn' => '聊城',
			'py' => 'liaocheng',
		),
		'dr' => array (
			'l' => 'L',
			'en' => 'dr',
			'cn' => '鹿邑',
			'py' => 'luyi',
		),
		'ip' => array (
			'l' => 'L',
			'en' => 'ip',
			'cn' => '黎平',
			'py' => 'liping',
		),
		'ix' => array (
			'l' => 'L',
			'en' => 'ix',
			'cn' => '临夏',
			'py' => 'linxia',
		),
		'ko' => array (
			'l' => 'L',
			'en' => 'ko',
			'cn' => '兰考',
			'py' => 'lankao',
		),
		'lanzhou' => array (
			'l' => 'L',
			'en' => 'lanzhou',
			'cn' => '兰州',
			'py' => 'lanzhou',
		),
		'lb' => array (
			'l' => 'L',
			'en' => 'lb',
			'cn' => '临沂',
			'py' => 'linyi',
		),
		'le' => array (
			'l' => 'L',
			'en' => 'le',
			'cn' => '漯河',
			'py' => 'luohe',
		),
		'leshan' => array (
			'l' => 'L',
			'en' => 'leshan',
			'cn' => '乐山',
			'py' => 'leshan',
		),
		'lf' => array (
			'l' => 'L',
			'en' => 'lf',
			'cn' => '廊坊',
			'py' => 'langfang',
		),
		'lg' => array (
			'l' => 'L',
			'en' => 'lg',
			'cn' => '凉山',
			'py' => 'liangshan',
		),
		'lh' => array (
			'l' => 'L',
			'en' => 'lh',
			'cn' => '林芝',
			'py' => 'linzhi',
		),
		'li' => array (
			'l' => 'L',
			'en' => 'li',
			'cn' => '辽源',
			'py' => 'liaoyuan',
		),
		'liuzhou' => array (
			'l' => 'L',
			'en' => 'liuzhou',
			'cn' => '柳州',
			'py' => 'liuzhou',
		),
		'lk' => array (
			'l' => 'L',
			'en' => 'lk',
			'cn' => '丽水',
			'py' => 'lishui',
		),
		'll' => array (
			'l' => 'L',
			'en' => 'll',
			'cn' => '吕梁',
			'py' => 'lvliang',
		),
		'ln' => array (
			'l' => 'L',
			'en' => 'ln',
			'cn' => '临汾',
			'py' => 'linfen',
		),
		'lo' => array (
			'l' => 'L',
			'en' => 'lo',
			'cn' => '龙岩',
			'py' => 'longyan',
		),
		'loudi' => array (
			'l' => 'L',
			'en' => 'loudi',
			'cn' => '娄底',
			'py' => 'loudi',
		),
		'lp' => array (
			'l' => 'L',
			'en' => 'lp',
			'cn' => '六盘水',
			'py' => 'liupanshui',
		),
		'lq' => array (
			'l' => 'L',
			'en' => 'lq',
			'cn' => '临沧',
			'py' => 'lincang',
		),
		'lt' => array (
			'l' => 'L',
			'en' => 'lt',
			'cn' => '来宾',
			'py' => 'laibin',
		),
		'luzhou' => array (
			'l' => 'L',
			'en' => 'luzhou',
			'cn' => '泸州',
			'py' => 'luzhou',
		),
		'lw' => array (
			'l' => 'L',
			'en' => 'lw',
			'cn' => '莱芜',
			'py' => 'laiwu',
		),
		'lx' => array (
			'l' => 'L',
			'en' => 'lx',
			'cn' => '辽阳',
			'py' => 'liaoyang',
		),
		'ly' => array (
			'l' => 'L',
			'en' => 'ly',
			'cn' => '洛阳',
			'py' => 'luoyang',
		),
		'on' => array (
			'l' => 'L',
			'en' => 'on',
			'cn' => '陇南',
			'py' => 'longnan',
		),
		'un' => array (
			'l' => 'L',
			'en' => 'un',
			'cn' => '六安',
			'py' => 'la',
		),
		'xi' => array (
			'l' => 'L',
			'en' => 'xi',
			'cn' => '拉萨',
			'py' => 'lasa',
		),
		'yg' => array (
			'l' => 'L',
			'en' => 'yg',
			'cn' => '连云港',
			'py' => 'lianyugang',
		),
		'mas' => array (
			'l' => 'M',
			'en' => 'mas',
			'cn' => '马鞍山',
			'py' => 'maanshan',
		),
		'md' => array (
			'l' => 'M',
			'en' => 'md',
			'cn' => '牡丹江',
			'py' => 'mudanjiang',
		),
		'me' => array (
			'l' => 'M',
			'en' => 'me',
			'cn' => '麻城',
			'py' => 'macheng',
		),
		'meishan' => array (
			'l' => 'M',
			'en' => 'meishan',
			'cn' => '眉山',
			'py' => 'meishan',
		),
		'mh' => array (
			'l' => 'M',
			'en' => 'mh',
			'cn' => '梅河口',
			'py' => 'meihekou',
		),
		'mianyang' => array (
			'l' => 'M',
			'en' => 'mianyang',
			'cn' => '绵阳',
			'py' => 'mianyang',
		),
		'mm' => array (
			'l' => 'M',
			'en' => 'mm',
			'cn' => '茂名',
			'py' => 'maoming',
		),
		'mz' => array (
			'l' => 'M',
			'en' => 'mz',
			'cn' => '梅州',
			'py' => 'meizhou',
		),
		'en' => array (
			'l' => 'N',
			'en' => 'en',
			'cn' => '南城',
			'py' => 'nancheng',
		),
		'gx' => array (
			'l' => 'N',
			'en' => 'gx',
			'cn' => '南宁',
			'py' => 'nanning',
		),
		'nanchong' => array (
			'l' => 'N',
			'en' => 'nanchong',
			'cn' => '南充',
			'py' => 'nanchong',
		),
		'nanjing' => array (
			'l' => 'N',
			'en' => 'nanjing',
			'cn' => '南京',
			'py' => 'nanjing',
		),
		'nb' => array (
			'l' => 'N',
			'en' => 'nb',
			'cn' => '宁波',
			'py' => 'ningbo',
		),
		'nc' => array (
			'l' => 'N',
			'en' => 'nc',
			'cn' => '南昌',
			'py' => 'nanchang',
		),
		'nd' => array (
			'l' => 'N',
			'en' => 'nd',
			'cn' => '宁德',
			'py' => 'ningde',
		),
		'ni' => array (
			'l' => 'N',
			'en' => 'ni',
			'cn' => '怒江',
			'py' => 'nujiang',
		),
		'np' => array (
			'l' => 'N',
			'en' => 'np',
			'cn' => '南平',
			'py' => 'nanping',
		),
		'nq' => array (
			'l' => 'N',
			'en' => 'nq',
			'cn' => '那曲',
			'py' => 'naqu',
		),
		'nt' => array (
			'l' => 'N',
			'en' => 'nt',
			'cn' => '南通',
			'py' => 'nantong',
		),
		'nu' => array (
			'l' => 'N',
			'en' => 'nu',
			'cn' => '内江',
			'py' => 'neijiang',
		),
		'ny' => array (
			'l' => 'N',
			'en' => 'ny',
			'cn' => '南阳',
			'py' => 'nanyang',
		),
		'pd' => array (
			'l' => 'P',
			'en' => 'pd',
			'cn' => '平顶山',
			'py' => 'pingdingshan',
		),
		'pe' => array (
			'l' => 'P',
			'en' => 'pe',
			'cn' => '普洱',
			'py' => 'puer',
		),
		'pj' => array (
			'l' => 'P',
			'en' => 'pj',
			'cn' => '盘锦',
			'py' => 'panjin',
		),
		'pl' => array (
			'l' => 'P',
			'en' => 'pl',
			'cn' => '平凉',
			'py' => 'pingliang',
		),
		'po' => array (
			'l' => 'P',
			'en' => 'po',
			'cn' => '鄱阳',
			'py' => 'poyang',
		),
		'pu' => array (
			'l' => 'P',
			'en' => 'pu',
			'cn' => '莆田',
			'py' => 'putian',
		),
		'px' => array (
			'l' => 'P',
			'en' => 'px',
			'cn' => '萍乡',
			'py' => 'pingxiang',
		),
		'pz' => array (
			'l' => 'P',
			'en' => 'pz',
			'cn' => '濮阳',
			'py' => 'puyang',
		),
		'pzh' => array (
			'l' => 'P',
			'en' => 'pzh',
			'cn' => '攀枝花',
			'py' => 'panzhihua',
		),
		'dn' => array (
			'l' => 'Q',
			'en' => 'dn',
			'cn' => '黔东南',
			'py' => 'qiandongnan',
		),
		'qa' => array (
			'l' => 'Q',
			'en' => 'qa',
			'cn' => '潜江',
			'py' => 'qianjiang',
		),
		'qb' => array (
			'l' => 'Q',
			'en' => 'qb',
			'cn' => '黔南布依族苗族自治州',
			'py' => 'qiannan',
		),
		'qc' => array (
			'l' => 'Q',
			'en' => 'qc',
			'cn' => '蕲春',
			'py' => 'qichun',
		),
		'qd' => array (
			'l' => 'Q',
			'en' => 'qd',
			'cn' => '青岛',
			'py' => 'qingdao',
		),
		'qg' => array (
			'l' => 'Q',
			'en' => 'qg',
			'cn' => '庆阳',
			'py' => 'qingyang',
		),
		'qhd' => array (
			'l' => 'Q',
			'en' => 'qhd',
			'cn' => '秦皇岛',
			'py' => 'qinhuangdao',
		),
		'qinzhou' => array (
			'l' => 'Q',
			'en' => 'qinzhou',
			'cn' => '钦州',
			'py' => 'qinzhou',
		),
		'qj' => array (
			'l' => 'Q',
			'en' => 'qj',
			'cn' => '曲靖',
			'py' => 'qujing',
		),
		'qo' => array (
			'l' => 'Q',
			'en' => 'qo',
			'cn' => '启东',
			'py' => 'qidong',
		),
		'qq' => array (
			'l' => 'Q',
			'en' => 'qq',
			'cn' => '齐齐哈尔',
			'py' => 'qiqihaer',
		),
		'qt' => array (
			'l' => 'Q',
			'en' => 'qt',
			'cn' => '七台河',
			'py' => 'qitaihe',
		),
		'quanzhou' => array (
			'l' => 'Q',
			'en' => 'quanzhou',
			'cn' => '泉州',
			'py' => 'quanzhou',
		),
		'qw' => array (
			'l' => 'Q',
			'en' => 'qw',
			'cn' => '衢州',
			'py' => 'quzhou',
		),
		'qx' => array (
			'l' => 'Q',
			'en' => 'qx',
			'cn' => '黔西南',
			'py' => 'qianxinan',
		),
		'qy' => array (
			'l' => 'Q',
			'en' => 'qy',
			'cn' => '清远',
			'py' => 'qingyuan',
		),
		'rj' => array (
			'l' => 'R',
			'en' => 'rj',
			'cn' => '瑞金',
			'py' => 'ruijin',
		),
		'rk' => array (
			'l' => 'R',
			'en' => 'rk',
			'cn' => '日喀则',
			'py' => 'rikaze',
		),
		'ru' => array (
			'l' => 'R',
			'en' => 'ru',
			'cn' => '汝州',
			'py' => 'ruzhou',
		),
		'rz' => array (
			'l' => 'R',
			'en' => 'rz',
			'cn' => '日照',
			'py' => 'rizhao',
		),
		'am' => array (
			'l' => 'S',
			'en' => 'am',
			'cn' => '三明',
			'py' => 'sanming',
		),
		'fh' => array (
			'l' => 'S',
			'en' => 'fh',
			'cn' => '绥芬河',
			'py' => 'suifenhe',
		),
		'mu' => array (
			'l' => 'S',
			'en' => 'mu',
			'cn' => '神木',
			'py' => 'shenmu',
		),
		'mx' => array (
			'l' => 'S',
			'en' => 'mx',
			'cn' => '三门峡',
			'py' => 'sanmenxia',
		),
		'no' => array (
			'l' => 'S',
			'en' => 'no',
			'cn' => '神农架',
			'py' => 'shennongjia',
		),
		'oy' => array (
			'l' => 'S',
			'en' => 'oy',
			'cn' => '松原',
			'py' => 'songyuan',
		),
		'sanya' => array (
			'l' => 'S',
			'en' => 'sanya',
			'cn' => '三亚',
			'py' => 'sanya',
		),
		'sb' => array (
			'l' => 'S',
			'en' => 'sb',
			'cn' => '邵阳',
			'py' => 'shaoyang',
		),
		'se' => array (
			'l' => 'S',
			'en' => 'se',
			'cn' => '朔州',
			'py' => 'shuozhou',
		),
		'sf' => array (
			'l' => 'S',
			'en' => 'sf',
			'cn' => '石嘴山',
			'py' => 'shizuishan',
		),
		'sg' => array (
			'l' => 'S',
			'en' => 'sg',
			'cn' => '韶关',
			'py' => 'shaoguan',
		),
		'sh' => array (
			'l' => 'S',
			'en' => 'sh',
			'cn' => '上海',
			'py' => 'shanghai',
		),
		'shantou' => array (
			'l' => 'S',
			'en' => 'shantou',
			'cn' => '汕头',
			'py' => 'shantou',
		),
		'shaoxing' => array (
			'l' => 'S',
			'en' => 'shaoxing',
			'cn' => '绍兴',
			'py' => 'shaoxing',
		),
		'si' => array (
			'l' => 'S',
			'en' => 'si',
			'cn' => '十堰',
			'py' => 'shiyan',
		),
		'sjz' => array (
			'l' => 'S',
			'en' => 'sjz',
			'cn' => '石家庄',
			'py' => 'shijiazhuang',
		),
		'sk' => array (
			'l' => 'S',
			'en' => 'sk',
			'cn' => '双鸭山',
			'py' => 'shuangyashan',
		),
		'sl' => array (
			'l' => 'S',
			'en' => 'sl',
			'cn' => '山南',
			'py' => 'shannan',
		),
		'sm' => array (
			'l' => 'S',
			'en' => 'sm',
			'cn' => '商丘',
			'py' => 'shangqiu',
		),
		'sp' => array (
			'l' => 'S',
			'en' => 'sp',
			'cn' => '四平',
			'py' => 'siping',
		),
		'sq' => array (
			'l' => 'S',
			'en' => 'sq',
			'cn' => '宿迁',
			'py' => 'suqian',
		),
		'sr' => array (
			'l' => 'S',
			'en' => 'sr',
			'cn' => '上饶',
			'py' => 'shangrao',
		),
		'suining' => array (
			'l' => 'S',
			'en' => 'suining',
			'cn' => '遂宁',
			'py' => 'suining',
		),
		'suzhou' => array (
			'l' => 'S',
			'en' => 'suzhou',
			'cn' => '苏州',
			'py' => 'suzhou',
		),
		'sv' => array (
			'l' => 'S',
			'en' => 'sv',
			'cn' => '绥化',
			'py' => 'suihua',
		),
		'sw' => array (
			'l' => 'S',
			'en' => 'sw',
			'cn' => '汕尾',
			'py' => 'shanwei',
		),
		'sy' => array (
			'l' => 'S',
			'en' => 'sy',
			'cn' => '沈阳',
			'py' => 'shenyang',
		),
		'sz' => array (
			'l' => 'S',
			'en' => 'sz',
			'cn' => '深圳',
			'py' => 'shenzhen',
		),
		'uh' => array (
			'l' => 'S',
			'en' => 'uh',
			'cn' => '绥中',
			'py' => 'suizhong',
		),
		'ui' => array (
			'l' => 'S',
			'en' => 'ui',
			'cn' => '随州',
			'py' => 'suizhou',
		),
		'uo' => array (
			'l' => 'S',
			'en' => 'uo',
			'cn' => '商洛',
			'py' => 'shangluo',
		),
		'us' => array (
			'l' => 'S',
			'en' => 'us',
			'cn' => '宿松',
			'py' => 'susong',
		),
		'uz' => array (
			'l' => 'S',
			'en' => 'uz',
			'cn' => '宿州',
			'py' => 'suzhou',
		),
		'taian' => array (
			'l' => 'T',
			'en' => 'taian',
			'cn' => '泰安',
			'py' => 'taian',
		),
		'taizhou' => array (
			'l' => 'T',
			'en' => 'taizhou',
			'cn' => '台州',
			'py' => 'taizhou',
		),
		'tangshan' => array (
			'l' => 'T',
			'en' => 'tangshan',
			'cn' => '唐山',
			'py' => 'tangshan',
		),
		'tb' => array (
			'l' => 'T',
			'en' => 'tb',
			'cn' => '泰州',
			'py' => 'taizhou',
		),
		'tc' => array (
			'l' => 'T',
			'en' => 'tc',
			'cn' => '太仓',
			'py' => 'taicang',
		),
		'te' => array (
			'l' => 'T',
			'en' => 'te',
			'cn' => '铜川',
			'py' => 'tongchuan',
		),
		'th' => array (
			'l' => 'T',
			'en' => 'th',
			'cn' => '通化',
			'py' => 'tonghua',
		),
		'ti' => array (
			'l' => 'T',
			'en' => 'ti',
			'cn' => '天水',
			'py' => 'tianshui',
		),
		'tj' => array (
			'l' => 'T',
			'en' => 'tj',
			'cn' => '天津',
			'py' => 'tianjin',
		),
		'tl' => array (
			'l' => 'T',
			'en' => 'tl',
			'cn' => '铁岭',
			'py' => 'tieling',
		),
		'tm' => array (
			'l' => 'T',
			'en' => 'tm',
			'cn' => '天门',
			'py' => 'tianmen',
		),
		'tn' => array (
			'l' => 'T',
			'en' => 'tn',
			'cn' => '通辽',
			'py' => 'tongliao',
		),
		'to' => array (
			'l' => 'T',
			'en' => 'to',
			'cn' => '铜陵',
			'py' => 'tongling',
		),
		'tr' => array (
			'l' => 'T',
			'en' => 'tr',
			'cn' => '铜仁',
			'py' => 'tongren',
		),
		'tx' => array (
			'l' => 'T',
			'en' => 'tx',
			'cn' => '泰兴',
			'py' => 'taixing',
		),
		'ty' => array (
			'l' => 'T',
			'en' => 'ty',
			'cn' => '太原',
			'py' => 'taiyuan',
		),
		'ul' => array (
			'l' => 'W',
			'en' => 'ul',
			'cn' => '乌兰察布',
			'py' => 'wulanchabu',
		),
		'wa' => array (
			'l' => 'W',
			'en' => 'wa',
			'cn' => '乌海',
			'py' => 'wuhai',
		),
		'wb' => array (
			'l' => 'W',
			'en' => 'wb',
			'cn' => '吴中',
			'py' => 'wuzhong',
		),
		'weifang' => array (
			'l' => 'W',
			'en' => 'weifang',
			'cn' => '潍坊',
			'py' => 'weifang',
		),
		'weihai' => array (
			'l' => 'W',
			'en' => 'weihai',
			'cn' => '威海',
			'py' => 'weihai',
		),
		'wh' => array (
			'l' => 'W',
			'en' => 'wh',
			'cn' => '武汉',
			'py' => 'wuhan',
		),
		'wj' => array (
			'l' => 'W',
			'en' => 'wj',
			'cn' => '吴江',
			'py' => 'wujiang',
		),
		'wl' => array (
			'l' => 'W',
			'en' => 'wl',
			'cn' => '乌兰浩特',
			'py' => 'wulanhaote',
		),
		'wn' => array (
			'l' => 'W',
			'en' => 'wn',
			'cn' => '渭南',
			'py' => 'weinan',
		),
		'wo' => array (
			'l' => 'W',
			'en' => 'wo',
			'cn' => '梧州',
			'py' => 'wuzhou',
		),
		'ws' => array (
			'l' => 'W',
			'en' => 'ws',
			'cn' => '文山',
			'py' => 'wenshan',
		),
		'wu' => array (
			'l' => 'W',
			'en' => 'wu',
			'cn' => '芜湖',
			'py' => 'wuhu',
		),
		'ww' => array (
			'l' => 'W',
			'en' => 'ww',
			'cn' => '武威',
			'py' => 'wuwei',
		),
		'wx' => array (
			'l' => 'W',
			'en' => 'wx',
			'cn' => '无锡',
			'py' => 'wuxi',
		),
		'wz' => array (
			'l' => 'W',
			'en' => 'wz',
			'cn' => '温州',
			'py' => 'wenzhou',
		),
		'xj' => array (
			'l' => 'W',
			'en' => 'xj',
			'cn' => '乌鲁木齐',
			'py' => 'wulumuqi',
		),
		'ax' => array (
			'l' => 'X',
			'en' => 'ax',
			'cn' => '仙桃',
			'py' => 'xiantao',
		),
		'ck' => array (
			'l' => 'X',
			'en' => 'ck',
			'cn' => '西昌',
			'py' => 'xichang',
		),
		'ge' => array (
			'l' => 'X',
			'en' => 'ge',
			'cn' => '锡林郭勒',
			'py' => 'xilinguole',
		),
		'hk' => array (
			'l' => 'X',
			'en' => 'hk',
			'cn' => '香港',
			'py' => 'xianggang',
		),
		'ib' => array (
			'l' => 'X',
			'en' => 'ib',
			'cn' => '湘西',
			'py' => 'xiangxi',
		),
		'im' => array (
			'l' => 'X',
			'en' => 'im',
			'cn' => '辛集',
			'py' => 'xinji',
		),
		'sx' => array (
			'l' => 'X',
			'en' => 'sx',
			'cn' => '西安',
			'py' => 'xian',
		),
		'uc' => array (
			'l' => 'X',
			'en' => 'uc',
			'cn' => '宣城',
			'py' => 'xuancheng',
		),
		'xa' => array (
			'l' => 'X',
			'en' => 'xa',
			'cn' => '邢台',
			'py' => 'xingtai',
		),
		'xb' => array (
			'l' => 'X',
			'en' => 'xb',
			'cn' => '信阳',
			'py' => 'xinyang',
		),
		'xc' => array (
			'l' => 'X',
			'en' => 'xc',
			'cn' => '忻州',
			'py' => 'xinzhou',
		),
		'xd' => array (
			'l' => 'X',
			'en' => 'xd',
			'cn' => '咸宁',
			'py' => 'xianning',
		),
		'xe' => array (
			'l' => 'X',
			'en' => 'xe',
			'cn' => '兴安盟',
			'py' => 'xinganmeng',
		),
		'xf' => array (
			'l' => 'X',
			'en' => 'xf',
			'cn' => '襄阳',
			'py' => 'xiangyang',
		),
		'xg' => array (
			'l' => 'X',
			'en' => 'xg',
			'cn' => '兴义',
			'py' => 'xingyi',
		),
		'xh' => array (
			'l' => 'X',
			'en' => 'xh',
			'cn' => '孝感',
			'py' => 'xiaogan',
		),
		'xiangtan' => array (
			'l' => 'X',
			'en' => 'xiangtan',
			'cn' => '湘潭',
			'py' => 'xiangtan',
		),
		'xining' => array (
			'l' => 'X',
			'en' => 'xining',
			'cn' => '西宁',
			'py' => 'xining',
		),
		'xm' => array (
			'l' => 'X',
			'en' => 'xm',
			'cn' => '厦门',
			'py' => 'xiamen',
		),
		'xo' => array (
			'l' => 'X',
			'en' => 'xo',
			'cn' => '新余',
			'py' => 'xinyu',
		),
		'xq' => array (
			'l' => 'X',
			'en' => 'xq',
			'cn' => '新蔡',
			'py' => 'xincai',
		),
		'xs' => array (
			'l' => 'X',
			'en' => 'xs',
			'cn' => '西双版纳',
			'py' => 'xishuangbanna',
		),
		'xu' => array (
			'l' => 'X',
			'en' => 'xu',
			'cn' => '许昌',
			'py' => 'xuchang',
		),
		'xx' => array (
			'l' => 'X',
			'en' => 'xx',
			'cn' => '新乡',
			'py' => 'xinxiang',
		),
		'xy' => array (
			'l' => 'X',
			'en' => 'xy',
			'cn' => '咸阳',
			'py' => 'xianyang',
		),
		'xz' => array (
			'l' => 'X',
			'en' => 'xz',
			'cn' => '徐州',
			'py' => 'xuzhou',
		),
		'ii' => array (
			'l' => 'Y',
			'en' => 'ii',
			'cn' => '伊犁',
			'py' => 'yili',
		),
		'og' => array (
			'l' => 'Y',
			'en' => 'og',
			'cn' => '永城',
			'py' => 'yongcheng',
		),
		'ub' => array (
			'l' => 'Y',
			'en' => 'ub',
			'cn' => '榆林',
			'py' => 'yulin',
		),
		'ur' => array (
			'l' => 'Y',
			'en' => 'ur',
			'cn' => '玉树',
			'py' => 'yushu',
		),
		'ya' => array (
			'l' => 'Y',
			'en' => 'ya',
			'cn' => '盐城',
			'py' => 'yancheng',
		),
		'yd' => array (
			'l' => 'Y',
			'en' => 'yd',
			'cn' => '扬州',
			'py' => 'yangzhou',
		),
		'ye' => array (
			'l' => 'Y',
			'en' => 'ye',
			'cn' => '延吉',
			'py' => 'yanji',
		),
		'yf' => array (
			'l' => 'Y',
			'en' => 'yf',
			'cn' => '云浮',
			'py' => 'yunfu',
		),
		'yh' => array (
			'l' => 'Y',
			'en' => 'yh',
			'cn' => '雅安',
			'py' => 'yaan',
		),
		'yibin' => array (
			'l' => 'Y',
			'en' => 'yibin',
			'cn' => '宜宾',
			'py' => 'yibin',
		),
		'yichang' => array (
			'l' => 'Y',
			'en' => 'yichang',
			'cn' => '宜昌',
			'py' => 'yichang',
		),
		'yinchuan' => array (
			'l' => 'Y',
			'en' => 'yinchuan',
			'cn' => '银川',
			'py' => 'yinchuan',
		),
		'yiyang' => array (
			'l' => 'Y',
			'en' => 'yiyang',
			'cn' => '益阳',
			'py' => 'yiyang',
		),
		'yj' => array (
			'l' => 'Y',
			'en' => 'yj',
			'cn' => '阳江',
			'py' => 'yangjiang',
		),
		'yk' => array (
			'l' => 'Y',
			'en' => 'yk',
			'cn' => '营口',
			'py' => 'yingkou',
		),
		'yl' => array (
			'l' => 'Y',
			'en' => 'yl',
			'cn' => '玉林',
			'py' => 'yulin',
		),
		'ym' => array (
			'l' => 'Y',
			'en' => 'ym',
			'cn' => '伊春',
			'py' => 'yichun',
		),
		'yongzhou' => array (
			'l' => 'Y',
			'en' => 'yongzhou',
			'cn' => '永州',
			'py' => 'yongzhou',
		),
		'yq' => array (
			'l' => 'Y',
			'en' => 'yq',
			'cn' => '阳泉',
			'py' => 'yangquan',
		),
		'yr' => array (
			'l' => 'Y',
			'en' => 'yr',
			'cn' => '鹰潭',
			'py' => 'yingtan',
		),
		'ys' => array (
			'l' => 'Y',
			'en' => 'ys',
			'cn' => '玉溪',
			'py' => 'yuxi',
		),
		'yt' => array (
			'l' => 'Y',
			'en' => 'yt',
			'cn' => '烟台',
			'py' => 'yantai',
		),
		'yu' => array (
			'l' => 'Y',
			'en' => 'yu',
			'cn' => '运城',
			'py' => 'yuncheng',
		),
		'yueyang' => array (
			'l' => 'Y',
			'en' => 'yueyang',
			'cn' => '岳阳',
			'py' => 'yueyang',
		),
		'yw' => array (
			'l' => 'Y',
			'en' => 'yw',
			'cn' => '义乌',
			'py' => 'yiwu',
		),
		'yx' => array (
			'l' => 'Y',
			'en' => 'yx',
			'cn' => '宜兴',
			'py' => 'yixing',
		),
		'zi' => array (
			'l' => 'Y',
			'en' => 'zi',
			'cn' => '延安',
			'py' => 'yanan',
		),
		'ey' => array (
			'l' => 'Z',
			'en' => 'ey',
			'cn' => '镇远',
			'py' => 'zhenyuan',
		),
		'hn' => array (
			'l' => 'Z',
			'en' => 'hn',
			'cn' => '郑州',
			'py' => 'zhengzhou',
		),
		'jg' => array (
			'l' => 'Z',
			'en' => 'jg',
			'cn' => '张家港',
			'py' => 'zhangjiagang',
		),
		'zb' => array (
			'l' => 'Z',
			'en' => 'zb',
			'cn' => '淄博',
			'py' => 'zibo',
		),
		'zc' => array (
			'l' => 'Z',
			'en' => 'zc',
			'cn' => '湛江',
			'py' => 'zhanjiang',
		),
		'zd' => array (
			'l' => 'Z',
			'en' => 'zd',
			'cn' => '镇江',
			'py' => 'zhenjiang',
		),
		'ze' => array (
			'l' => 'Z',
			'en' => 'ze',
			'cn' => '舟山',
			'py' => 'zhoushan',
		),
		'zhongshan' => array (
			'l' => 'Z',
			'en' => 'zhongshan',
			'cn' => '中山',
			'py' => 'zhongshan',
		),
		'zhuhai' => array (
			'l' => 'Z',
			'en' => 'zhuhai',
			'cn' => '珠海',
			'py' => 'zhuhai',
		),
		'zigong' => array (
			'l' => 'Z',
			'en' => 'zigong',
			'cn' => '自贡',
			'py' => 'zigong',
		),
		'zjj' => array (
			'l' => 'Z',
			'en' => 'zjj',
			'cn' => '张家界',
			'py' => 'zhangjiajie',
		),
		'zjk' => array (
			'l' => 'Z',
			'en' => 'zjk',
			'cn' => '张家口',
			'py' => 'zhangjiakou',
		),
		'zk' => array (
			'l' => 'Z',
			'en' => 'zk',
			'cn' => '周口',
			'py' => 'zhoukou',
		),
		'zm' => array (
			'l' => 'Z',
			'en' => 'zm',
			'cn' => '驻马店',
			'py' => 'zhumadian',
		),
		'zn' => array (
			'l' => 'Z',
			'en' => 'zn',
			'cn' => '张掖',
			'py' => 'zhangye',
		),
		'zo' => array (
			'l' => 'Z',
			'en' => 'zo',
			'cn' => '漳州',
			'py' => 'zhangzhou',
		),
		'zp' => array (
			'l' => 'Z',
			'en' => 'zp',
			'cn' => '诸暨',
			'py' => 'zhuji',
		),
		'zq' => array (
			'l' => 'Z',
			'en' => 'zq',
			'cn' => '肇庆',
			'py' => 'zhaoqing',
		),
		'zr' => array (
			'l' => 'Z',
			'en' => 'zr',
			'cn' => '资阳',
			'py' => 'ziyang',
		),
		'zt' => array (
			'l' => 'Z',
			'en' => 'zt',
			'cn' => '昭通',
			'py' => 'zhaotong',
		),
		'zu' => array (
			'l' => 'Z',
			'en' => 'zu',
			'cn' => '枣庄',
			'py' => 'zaozhuang',
		),
		'zw' => array (
			'l' => 'Z',
			'en' => 'zw',
			'cn' => '中卫',
			'py' => 'zhongwei',
		),
		'zy' => array (
			'l' => 'Z',
			'en' => 'zy',
			'cn' => '遵义',
			'py' => 'zunyi',
		),
		'zz' => array (
			'l' => 'Z',
			'en' => 'zz',
			'cn' => '株洲',
			'py' => 'zhuzhou',
		),
	),
	// CMS key 为 city_pub value.en 为 city_en
	'CMS' => array (
		'alsm' => array(
			'en' => 'aa',
			'cn' => '阿拉善盟',
			'py' => 'alashanmeng',
		),
		'aba' => array(
			'en' => 'ab',
			'cn' => '阿坝',
			'py' => 'aba',
		),
		'liaocheng' => array(
			'en' => 'ac',
			'cn' => '聊城',
			'py' => 'liaocheng',
		),
		'ad' => array(
			'en' => 'ad',
			'cn' => '澳大利亚',
			'py' => 'aodaliya',
		),
		'ae' => array(
			'en' => 'ae',
			'cn' => '阿联酋',
			'py' => 'alianqiu',
		),
		'anfu' => array(
			'en' => 'af',
			'cn' => '安福',
			'py' => 'anfu',
		),
		'jinchang' => array(
			'en' => 'ag',
			'cn' => '金昌',
			'py' => 'jinchang',
		),
		'anqing' => array(
			'en' => 'ai',
			'cn' => '安庆',
			'py' => 'anqing',
		),
		'baoji' => array(
			'en' => 'aj',
			'cn' => '宝鸡',
			'py' => 'baoji',
		),
		'ankang' => array(
			'en' => 'ak',
			'cn' => '安康',
			'py' => 'ankang',
		),
		'ali' => array(
			'en' => 'al',
			'cn' => '阿里',
			'py' => 'ali',
		),
		'sanming' => array(
			'en' => 'am',
			'cn' => '三明',
			'py' => 'sanming',
		),
		'anshun' => array(
			'en' => 'an',
			'cn' => '安顺',
			'py' => 'anshun',
		),
		'anshan' => array(
			'en' => 'anshan',
			'cn' => '鞍山',
			'py' => 'anshan',
		),
		'xiantao' => array(
			'en' => 'ax',
			'cn' => '仙桃',
			'py' => 'xiantao',
		),
		'anyang' => array(
			'en' => 'ay',
			'cn' => '安阳',
			'py' => 'anyang',
		),
		'hanzhong' => array(
			'en' => 'az',
			'cn' => '汉中',
			'py' => 'hanzhong',
		),
		'bd' => array(
			'en' => 'baoding',
			'cn' => '保定',
			'py' => 'baoding',
		),
		'bengbu' => array(
			'en' => 'bb',
			'cn' => '蚌埠',
			'py' => 'bengbu',
		),
		'baise' => array(
			'en' => 'bc',
			'cn' => '百色',
			'py' => 'baise',
		),
		'bijie' => array(
			'en' => 'be',
			'cn' => '毕节',
			'py' => 'bijie',
		),
		'beihai' => array(
			'en' => 'beihai',
			'cn' => '北海',
			'py' => 'beihai',
		),
		'baicheng' => array(
			'en' => 'bf',
			'cn' => '白城',
			'py' => 'baicheng',
		),
		'bygl' => array(
			'en' => 'bg',
			'cn' => '巴音郭楞',
			'py' => 'bayinguoleng',
		),
		'bi' => array(
			'en' => 'bi',
			'cn' => '英国',
			'py' => 'yingguo',
		),
		'bj' => array(
			'en' => 'bj',
			'cn' => '北京',
			'py' => 'beijing',
		),
		'baishan' => array(
			'en' => 'bk',
			'cn' => '白山',
			'py' => 'baishan',
		),
		'bm' => array(
			'en' => 'bm',
			'cn' => '巴哈马联邦',
			'py' => 'bahama',
		),
		'binzhou' => array(
			'en' => 'bn',
			'cn' => '滨州',
			'py' => 'binzhou',
		),
		'bozhou' => array(
			'en' => 'bo',
			'cn' => '亳州',
			'py' => 'bozhou',
		),
		'boao' => array(
			'en' => 'boao',
			'cn' => '博鳌',
			'py' => 'boao',
		),
		'baoshan' => array(
			'en' => 'bs',
			'cn' => '保山',
			'py' => 'baoshan',
		),
		'bt' => array(
			'en' => 'bt',
			'cn' => '包头',
			'py' => 'baotou',
		),
		'benxi' => array(
			'en' => 'bx',
			'cn' => '本溪',
			'py' => 'benxi',
		),
		'by' => array(
			'en' => 'by',
			'cn' => '西班牙',
			'py' => 'xibanya',
		),
		'bazhong' => array(
			'en' => 'bz',
			'cn' => '巴中',
			'py' => 'bazhong',
		),
		'chengde' => array(
			'en' => 'ce',
			'cn' => '承德',
			'py' => 'chengde',
		),
		'chifeng' => array(
			'en' => 'cf',
			'cn' => '赤峰',
			'py' => 'chifeng',
		),
		'changdu' => array(
			'en' => 'cg',
			'cn' => '昌都',
			'py' => 'changdu',
		),
		'changde' => array(
			'en' => 'changde',
			'cn' => '常德',
			'py' => 'changde',
		),
		'changshu' => array(
			'en' => 'changshu',
			'cn' => '常熟',
			'py' => 'changshu',
		),
		'chenzhou' => array(
			'en' => 'chenzhou',
			'cn' => '郴州',
			'py' => 'chenzhou',
		),
		'changzhi' => array(
			'en' => 'ci',
			'cn' => '长治',
			'py' => 'changzhi',
		),
		'chuzhou' => array(
			'en' => 'cj',
			'cn' => '滁州',
			'py' => 'chuzhou',
		),
		'xichang' => array(
			'en' => 'ck',
			'cn' => '西昌',
			'py' => 'xichang',
		),
		'chaohu' => array(
			'en' => 'cl',
			'cn' => '巢湖',
			'py' => 'chaohu',
		),
		'changyuan' => array(
			'en' => 'cm',
			'cn' => '长垣',
			'py' => 'changyuan',
		),
		'changtu' => array(
			'en' => 'cn',
			'cn' => '昌图',
			'py' => 'changtu',
		),
		'cangzhou' => array(
			'en' => 'co',
			'cn' => '沧州',
			'py' => 'cangzhou',
		),
		'cp' => array(
			'en' => 'cp',
			'cn' => '塞浦路斯',
			'py' => 'saipulusi',
		),
		'cq' => array(
			'en' => 'cq',
			'cn' => '重庆',
			'py' => 'chongqing',
		),
		'cs' => array(
			'en' => 'cs',
			'cn' => '长沙',
			'py' => 'changsha',
		),
		'chongzuo' => array(
			'en' => 'ct',
			'cn' => '崇左',
			'py' => 'chongzuo',
		),
		'chaozhou' => array(
			'en' => 'cu',
			'cn' => '潮州',
			'py' => 'chaozhou',
		),
		'cw' => array(
			'en' => 'cw',
			'cn' => '圣基茨和尼维斯联邦',
			'py' => 'shengjiciheniweisili',
		),
		'chuxiong' => array(
			'en' => 'cx',
			'cn' => '楚雄',
			'py' => 'chuxiong',
		),
		'chaoyang' => array(
			'en' => 'cy',
			'cn' => '朝阳',
			'py' => 'chaoyang',
		),
		'cz' => array(
			'en' => 'cz',
			'cn' => '常州',
			'py' => 'changzhou',
		),
		'dali' => array(
			'en' => 'da',
			'cn' => '大理',
			'py' => 'dali',
		),
		'daqing' => array(
			'en' => 'daqing',
			'cn' => '大庆',
			'py' => 'daqing',
		),
		'dazhou' => array(
			'en' => 'dazhou',
			'cn' => '达州',
			'py' => 'dazhou',
		),
		'haidong' => array(
			'en' => 'db',
			'cn' => '海东',
			'py' => 'haidong',
		),
		'dingzhou' => array(
			'en' => 'dc',
			'cn' => '定州',
			'py' => 'dingzhou',
		),
		'dandong' => array(
			'en' => 'dd',
			'cn' => '丹东',
			'py' => 'dandong',
		),
		'deyang' => array(
			'en' => 'deyang',
			'cn' => '德阳',
			'py' => 'deyang',
		),
		'dg' => array(
			'en' => 'dg',
			'cn' => '东莞',
			'py' => 'dongguan',
		),
		'dehong' => array(
			'en' => 'dh',
			'cn' => '德宏',
			'py' => 'dehong',
		),
		'diqing' => array(
			'en' => 'di',
			'cn' => '迪庆',
			'py' => 'diqing',
		),
		'cj' => array(
			'en' => 'dj',
			'cn' => '昌吉',
			'py' => 'changji',
		),
		'dl' => array(
			'en' => 'dl',
			'cn' => '大连',
			'py' => 'dalian',
		),
		'qiandn' => array(
			'en' => 'dn',
			'cn' => '黔东南',
			'py' => 'qiandongnan',
		),
		'dengzhou' => array(
			'en' => 'do',
			'cn' => '邓州',
			'py' => 'dengzhou',
		),
		'luyi' => array(
			'en' => 'dr',
			'cn' => '鹿邑',
			'py' => 'luyi',
		),
		'datong' => array(
			'en' => 'dt',
			'cn' => '大同',
			'py' => 'datong',
		),
		'dezhou' => array(
			'en' => 'du',
			'cn' => '德州',
			'py' => 'dezhou',
		),
		'dingxi' => array(
			'en' => 'dx',
			'cn' => '定西',
			'py' => 'dingxi',
		),
		'dy' => array(
			'en' => 'dy',
			'cn' => '东营',
			'py' => 'dongying',
		),
		'haibei' => array(
			'en' => 'ea',
			'cn' => '海北',
			'py' => 'haibei',
		),
		'eeds' => array(
			'en' => 'eeds',
			'cn' => '鄂尔多斯',
			'py' => 'eerduosi',
		),
		'hegang' => array(
			'en' => 'eg',
			'cn' => '鹤岗',
			'py' => 'hegang',
		),
		'heze' => array(
			'en' => 'eh',
			'cn' => '菏泽',
			'py' => 'heze',
		),
		'heihe' => array(
			'en' => 'ei',
			'cn' => '黑河',
			'py' => 'heihe',
		),
		'nancheng' => array(
			'en' => 'en',
			'cn' => '南城',
			'py' => 'nancheng',
		),
		'hlbe' => array(
			'en' => 'er',
			'cn' => '呼伦贝尔',
			'py' => 'hulunbeier',
		),
		'enshi' => array(
			'en' => 'es',
			'cn' => '恩施',
			'py' => 'enshi',
		),
		'zhenyuan' => array(
			'en' => 'ey',
			'cn' => '镇远',
			'py' => 'zhenyuan',
		),
		'ezhou' => array(
			'en' => 'ez',
			'cn' => '鄂州',
			'py' => 'ezhou',
		),
		'fushun' => array(
			'en' => 'fa',
			'cn' => '抚顺',
			'py' => 'fushun',
		),
		'fcg' => array(
			'en' => 'fcg',
			'cn' => '防城港',
			'py' => 'fangchenggang',
		),
		'fengcheng' => array(
			'en' => 'fe',
			'cn' => '丰城',
			'py' => 'fengcheng',
		),
		'fugu' => array(
			'en' => 'fg',
			'cn' => '府谷',
			'py' => 'fugu',
		),
		'sfh' => array(
			'en' => 'fh',
			'cn' => '绥芬河',
			'py' => 'suifenhe',
		),
		'fj' => array(
			'en' => 'fj',
			'cn' => '福州',
			'py' => 'fuzhou',
		),
		'fuzhou' => array(
			'en' => 'fo',
			'cn' => '抚州',
			'py' => 'fuzhou',
		),
		'fuquan' => array(
			'en' => 'fq',
			'cn' => '福泉',
			'py' => 'fuquan',
		),
		'fr' => array(
			'en' => 'fr',
			'cn' => '法国',
			'py' => 'faguo',
		),
		'fs' => array(
			'en' => 'fs',
			'cn' => '佛山',
			'py' => 'foshan',
		),
		'fuyuan' => array(
			'en' => 'fu',
			'cn' => '抚远',
			'py' => 'fuyuan',
		),
		'fuxin' => array(
			'en' => 'fx',
			'cn' => '阜新',
			'py' => 'fuxin',
		),
		'fuyang' => array(
			'en' => 'fy',
			'cn' => '阜阳',
			'py' => 'fuyang',
		),
		'guangan' => array(
			'en' => 'ga',
			'cn' => '广安',
			'py' => 'guangan',
		),
		'ganzhou' => array(
			'en' => 'ganzhou',
			'cn' => '赣州',
			'py' => 'ganzhou',
		),
		'gannan' => array(
			'en' => 'gb',
			'cn' => '甘南',
			'py' => 'gannan',
		),
		'guyuan' => array(
			'en' => 'gc',
			'cn' => '固原',
			'py' => 'guyuan',
		),
		'guangde' => array(
			'en' => 'gd',
			'cn' => '广德',
			'py' => 'guangde',
		),
		'xlgl' => array(
			'en' => 'ge',
			'cn' => '锡林郭勒',
			'py' => 'xilinguole',
		),
		'guoluo' => array(
			'en' => 'gf',
			'cn' => '果洛',
			'py' => 'guoluo',
		),
		'guigang' => array(
			'en' => 'gg',
			'cn' => '贵港',
			'py' => 'guigang',
		),
		'guangyuan' => array(
			'en' => 'gi',
			'cn' => '广元',
			'py' => 'guangyuan',
		),
		'gm' => array(
			'en' => 'gm',
			'cn' => '德国',
			'py' => 'deguo',
		),
		'gongyi' => array(
			'en' => 'go',
			'cn' => '巩义',
			'py' => 'gongyi',
		),
		'gqc' => array(
			'en' => 'gq',
			'cn' => '共青城',
			'py' => 'gongqingcheng',
		),
		'ganzi' => array(
			'en' => 'gs',
			'cn' => '甘孜',
			'py' => 'ganzi',
		),
		'gushi' => array(
			'en' => 'gu',
			'cn' => '固始',
			'py' => 'gushi',
		),
		'guilin' => array(
			'en' => 'guilin',
			'cn' => '桂林',
			'py' => 'guilin',
		),
		'guizhou' => array(
			'en' => 'guizhou',
			'cn' => '贵州',
			'py' => 'guizhou',
		),
		'gx' => array(
			'en' => 'gx',
			'cn' => '广西',
			'py' => 'guangxi',
		),
		'gz' => array(
			'en' => 'gz',
			'cn' => '广州',
			'py' => 'guangzhou',
		),
		'hrb' => array(
			'en' => 'h',
			'cn' => '哈尔滨',
			'py' => 'haerbin',
		),
		'han' => array(
			'en' => 'han',
			'cn' => '海南',
			'py' => 'hainan',
		),
		'handan' => array(
			'en' => 'handan',
			'cn' => '邯郸',
			'py' => 'handan',
		),
		'hz' => array(
			'en' => 'hangzhou',
			'cn' => '杭州',
			'py' => 'hangzhou',
		),
		'heyuan' => array(
			'en' => 'hb',
			'cn' => '河源',
			'py' => 'heyuan',
		),
		'huainan' => array(
			'en' => 'hc',
			'cn' => '淮南',
			'py' => 'huainan',
		),
		'huaibei' => array(
			'en' => 'he',
			'cn' => '淮北',
			'py' => 'huaibei',
		),
		'hengyang' => array(
			'en' => 'hengyang',
			'cn' => '衡阳',
			'py' => 'hengyang',
		),
		'hf' => array(
			'en' => 'hf',
			'cn' => '合肥',
			'py' => 'hefei',
		),
		'huanggang' => array(
			'en' => 'hg',
			'cn' => '黄冈',
			'py' => 'huanggang',
		),
		'hh' => array(
			'en' => 'hh',
			'cn' => '怀化',
			'py' => 'huaihua',
		),
		'hhht' => array(
			'en' => 'hhht',
			'cn' => '呼和浩特',
			'py' => 'huhehaote',
		),
		'huaian' => array(
			'en' => 'hj',
			'cn' => '淮安',
			'py' => 'huaian',
		),
		'hk' => array(
			'en' => 'hk',
			'cn' => '香港',
			'py' => 'xianggang',
		),
		'hld' => array(
			'en' => 'hl',
			'cn' => '葫芦岛',
			'py' => 'huludao',
		),
		'haimen' => array(
			'en' => 'hm',
			'cn' => '海门',
			'py' => 'haimen',
		),
		'hn' => array(
			'en' => 'hn',
			'cn' => '郑州',
			'py' => 'zhengzhou',
		),
		'huzhou' => array(
			'en' => 'ho',
			'cn' => '湖州',
			'py' => 'huzhou',
		),
		'honghe' => array(
			'en' => 'hq',
			'cn' => '红河',
			'py' => 'honghe',
		),
		'huangshan' => array(
			'en' => 'hr',
			'cn' => '黄山',
			'py' => 'huangshan',
		),
		'hengshui' => array(
			'en' => 'hs',
			'cn' => '衡水',
			'py' => 'hengshui',
		),
		'hezhou' => array(
			'en' => 'ht',
			'cn' => '贺州',
			'py' => 'hezhou',
		),
		'huangshi' => array(
			'en' => 'huangshi',
			'cn' => '黄石',
			'py' => 'huangshi',
		),
		'huizhou' => array(
			'en' => 'huizhou',
			'cn' => '惠州',
			'py' => 'huizhou',
		),
		'hebi' => array(
			'en' => 'hw',
			'cn' => '鹤壁',
			'py' => 'hebi',
		),
		'hechi' => array(
			'en' => 'hx',
			'cn' => '河池',
			'py' => 'hechi',
		),
		'baiyin' => array(
			'en' => 'ia',
			'cn' => '白银',
			'py' => 'baiyin',
		),
		'xiangxi' => array(
			'en' => 'ib',
			'cn' => '湘西',
			'py' => 'xiangxi',
		),
		'dxal' => array(
			'en' => 'ig',
			'cn' => '大兴安岭',
			'py' => 'daxinganling',
		),
		'hain' => array(
			'en' => 'ih',
			'cn' => '海南藏族自治州',
			'py' => 'hainanzangzuzizhizho',
		),
		'yili' => array(
			'en' => 'ii',
			'cn' => '伊犁',
			'py' => 'yili',
		),
		'xinji' => array(
			'en' => 'im',
			'cn' => '辛集',
			'py' => 'xinji',
		),
		'jn' => array(
			'en' => 'in',
			'cn' => '集宁',
			'py' => 'jining',
		),
		'liping' => array(
			'en' => 'ip',
			'cn' => '黎平',
			'py' => 'liping',
		),
		'it' => array(
			'en' => 'it',
			'cn' => '意大利',
			'py' => 'yidali',
		),
		'chizhou' => array(
			'en' => 'iu',
			'cn' => '池州',
			'py' => 'chizhou',
		),
		'linxia' => array(
			'en' => 'ix',
			'cn' => '临夏',
			'py' => 'linxia',
		),
		'jinzhou' => array(
			'en' => 'ja',
			'cn' => '锦州',
			'py' => 'jinzhou',
		),
		'jincheng' => array(
			'en' => 'jc',
			'cn' => '晋城',
			'py' => 'jincheng',
		),
		'jingmen' => array(
			'en' => 'jd',
			'cn' => '荆门',
			'py' => 'jingmen',
		),
		'jieyang' => array(
			'en' => 'je',
			'cn' => '揭阳',
			'py' => 'jieyang',
		),
		'jian' => array(
			'en' => 'jf',
			'cn' => '吉安',
			'py' => 'jian',
		),
		'zjg' => array(
			'en' => 'jg',
			'cn' => '张家港',
			'py' => 'zhangjiagang',
		),
		'jinhua' => array(
			'en' => 'jh',
			'cn' => '金华',
			'py' => 'jinhua',
		),
		'jiaozuo' => array(
			'en' => 'ji',
			'cn' => '焦作',
			'py' => 'jiaozuo',
		),
		'jiangmen' => array(
			'en' => 'jiangmen',
			'cn' => '江门',
			'py' => 'jiangmen',
		),
		'jilin' => array(
			'en' => 'jilin',
			'cn' => '吉林',
			'py' => 'jilin',
		),
		'jingzhou' => array(
			'en' => 'jingzhou',
			'cn' => '荆州',
			'py' => 'jingzhou',
		),
		'jinzhong' => array(
			'en' => 'jinzhong',
			'cn' => '晋中',
			'py' => 'jinzhong',
		),
		'jiujiang' => array(
			'en' => 'jiujiang',
			'cn' => '九江',
			'py' => 'jiujiang',
		),
		'jinmen' => array(
			'en' => 'jk',
			'cn' => '金门',
			'py' => 'jinmen',
		),
		'cc' => array(
			'en' => 'jl',
			'cn' => '长春',
			'py' => 'changchun',
		),
		'jining' => array(
			'en' => 'jn',
			'cn' => '济宁',
			'py' => 'jining',
		),
		'jiyuan' => array(
			'en' => 'jp',
			'cn' => '济源',
			'py' => 'jiyuan',
		),
		'jiuquan' => array(
			'en' => 'jq',
			'cn' => '酒泉',
			'py' => 'jiuquan',
		),
		'jishou' => array(
			'en' => 'js',
			'cn' => '吉首',
			'py' => 'jishou',
		),
		'jyg' => array(
			'en' => 'ju',
			'cn' => '嘉峪关',
			'py' => 'jiayuguan',
		),
		'jixi' => array(
			'en' => 'jv',
			'cn' => '鸡西',
			'py' => 'jixi',
		),
		'jdz' => array(
			'en' => 'jw',
			'cn' => '景德镇',
			'py' => 'jingdezhen',
		),
		'jiaxing' => array(
			'en' => 'jx',
			'cn' => '嘉兴',
			'py' => 'jiaxing',
		),
		'jiangyin' => array(
			'en' => 'jy',
			'cn' => '江阴',
			'py' => 'jiangyin',
		),
		'kashi' => array(
			'en' => 'ka',
			'cn' => '喀什',
			'py' => 'kashi',
		),
		'kf' => array(
			'en' => 'kf',
			'cn' => '开封',
			'py' => 'kaifeng',
		),
		'kaili' => array(
			'en' => 'kl',
			'cn' => '凯里',
			'py' => 'kaili',
		),
		'lankao' => array(
			'en' => 'ko',
			'cn' => '兰考',
			'py' => 'lankao',
		),
		'ks' => array(
			'en' => 'ks',
			'cn' => '昆山',
			'py' => 'kunshan',
		),
		'lz' => array(
			'en' => 'lanzhou',
			'cn' => '兰州',
			'py' => 'lanzhou',
		),
		'linyi' => array(
			'en' => 'lb',
			'cn' => '临沂',
			'py' => 'linyi',
		),
		'liyang' => array(
			'en' => 'lc',
			'cn' => '溧阳',
			'py' => 'liyang',
		),
		'luohe' => array(
			'en' => 'le',
			'cn' => '漯河',
			'py' => 'luohe',
		),
		'leshan' => array(
			'en' => 'leshan',
			'cn' => '乐山',
			'py' => 'leshan',
		),
		'langfang' => array(
			'en' => 'lf',
			'cn' => '廊坊',
			'py' => 'langfang',
		),
		'liangshan' => array(
			'en' => 'lg',
			'cn' => '凉山',
			'py' => 'liangshan',
		),
		'linzhi' => array(
			'en' => 'lh',
			'cn' => '林芝',
			'py' => 'linzhi',
		),
		'liaoyuan' => array(
			'en' => 'li',
			'cn' => '辽源',
			'py' => 'liaoyuan',
		),
		'liuzhou' => array(
			'en' => 'liuzhou',
			'cn' => '柳州',
			'py' => 'liuzhou',
		),
		'lishui' => array(
			'en' => 'lk',
			'cn' => '丽水',
			'py' => 'lishui',
		),
		'lvliang' => array(
			'en' => 'll',
			'cn' => '吕梁',
			'py' => 'lvliang',
		),
		'linfen' => array(
			'en' => 'ln',
			'cn' => '临汾',
			'py' => 'linfen',
		),
		'longyan' => array(
			'en' => 'lo',
			'cn' => '龙岩',
			'py' => 'longyan',
		),
		'loudi' => array(
			'en' => 'loudi',
			'cn' => '娄底',
			'py' => 'loudi',
		),
		'lps' => array(
			'en' => 'lp',
			'cn' => '六盘水',
			'py' => 'liupanshui',
		),
		'lincang' => array(
			'en' => 'lq',
			'cn' => '临沧',
			'py' => 'lincang',
		),
		'laibin' => array(
			'en' => 'lt',
			'cn' => '来宾',
			'py' => 'laibin',
		),
		'luzhou' => array(
			'en' => 'luzhou',
			'cn' => '泸州',
			'py' => 'luzhou',
		),
		'laiwu' => array(
			'en' => 'lw',
			'cn' => '莱芜',
			'py' => 'laiwu',
		),
		'liaoyang' => array(
			'en' => 'lx',
			'cn' => '辽阳',
			'py' => 'liaoyang',
		),
		'ly' => array(
			'en' => 'ly',
			'cn' => '洛阳',
			'py' => 'luoyang',
		),
		'mas' => array(
			'en' => 'mas',
			'cn' => '马鞍山',
			'py' => 'maanshan',
		),
		'macao' => array(
			'en' => 'mc',
			'cn' => '澳门',
			'py' => 'aomen',
		),
		'mdj' => array(
			'en' => 'md',
			'cn' => '牡丹江',
			'py' => 'mudanjiang',
		),
		'macheng' => array(
			'en' => 'me',
			'cn' => '麻城',
			'py' => 'macheng',
		),
		'meishan' => array(
			'en' => 'meishan',
			'cn' => '眉山',
			'py' => 'meishan',
		),
		'mg' => array(
			'en' => 'mg',
			'cn' => '美国',
			'py' => 'meiguo',
		),
		'mhk' => array(
			'en' => 'mh',
			'cn' => '梅河口',
			'py' => 'meihekou',
		),
		'hami' => array(
			'en' => 'mi',
			'cn' => '哈密',
			'py' => 'hami',
		),
		'mianyang' => array(
			'en' => 'mianyang',
			'cn' => '绵阳',
			'py' => 'mianyang',
		),
		'mj' => array(
			'en' => 'mj',
			'cn' => '加拿大',
			'py' => 'jianada',
		),
		'ml' => array(
			'en' => 'ml',
			'cn' => '马来西亚',
			'py' => 'malaixiya',
		),
		'maoming' => array(
			'en' => 'mm',
			'cn' => '茂名',
			'py' => 'maoming',
		),
		'shenmu' => array(
			'en' => 'mu',
			'cn' => '神木',
			'py' => 'shenmu',
		),
		'smx' => array(
			'en' => 'mx',
			'cn' => '三门峡',
			'py' => 'sanmenxia',
		),
		'meizhou' => array(
			'en' => 'mz',
			'cn' => '梅州',
			'py' => 'meizhou',
		),
		'nanchong' => array(
			'en' => 'nanchong',
			'cn' => '南充',
			'py' => 'nanchong',
		),
		'nj' => array(
			'en' => 'nanjing',
			'cn' => '南京',
			'py' => 'nanjing',
		),
		'nb' => array(
			'en' => 'nb',
			'cn' => '宁波',
			'py' => 'ningbo',
		),
		'nc' => array(
			'en' => 'nc',
			'cn' => '南昌',
			'py' => 'nanchang',
		),
		'ningde' => array(
			'en' => 'nd',
			'cn' => '宁德',
			'py' => 'ningde',
		),
		'byne' => array(
			'en' => 'ne',
			'cn' => '巴彦淖尔',
			'py' => 'bayannaoer',
		),
		'nujiang' => array(
			'en' => 'ni',
			'cn' => '怒江',
			'py' => 'nujiang',
		),
		'nk' => array(
			'en' => 'nk',
			'cn' => '韩国',
			'py' => 'hanguo',
		),
		'nn' => array(
			'en' => 'nn',
			'cn' => '海宁',
			'py' => 'haining',
		),
		'snj' => array(
			'en' => 'no',
			'cn' => '神农架',
			'py' => 'shennongjia',
		),
		'nanping' => array(
			'en' => 'np',
			'cn' => '南平',
			'py' => 'nanping',
		),
		'naqu' => array(
			'en' => 'nq',
			'cn' => '那曲',
			'py' => 'naqu',
		),
		'nt' => array(
			'en' => 'nt',
			'cn' => '南通',
			'py' => 'nantong',
		),
		'neijiang' => array(
			'en' => 'nu',
			'cn' => '内江',
			'py' => 'neijiang',
		),
		'huaxian' => array(
			'en' => 'nx',
			'cn' => '滑县',
			'py' => 'huaxian',
		),
		'nanyang' => array(
			'en' => 'ny',
			'cn' => '南阳',
			'py' => 'nanyang',
		),
		'od' => array(
			'en' => 'od',
			'cn' => '荷兰',
			'py' => 'helan',
		),
		'yongcheng' => array(
			'en' => 'og',
			'cn' => '永城',
			'py' => 'yongcheng',
		),
		'longnan' => array(
			'en' => 'on',
			'cn' => '陇南',
			'py' => 'longnan',
		),
		'songyuan' => array(
			'en' => 'oy',
			'cn' => '松原',
			'py' => 'songyuan',
		),
		'pds' => array(
			'en' => 'pd',
			'cn' => '平顶山',
			'py' => 'pingdingshan',
		),
		'puer' => array(
			'en' => 'pe',
			'cn' => '普洱',
			'py' => 'puer',
		),
		'panjin' => array(
			'en' => 'pj',
			'cn' => '盘锦',
			'py' => 'panjin',
		),
		'pingliang' => array(
			'en' => 'pl',
			'cn' => '平凉',
			'py' => 'pingliang',
		),
		'poyang' => array(
			'en' => 'po',
			'cn' => '鄱阳',
			'py' => 'poyang',
		),
		'putian' => array(
			'en' => 'pu',
			'cn' => '莆田',
			'py' => 'putian',
		),
		'pingxiang' => array(
			'en' => 'px',
			'cn' => '萍乡',
			'py' => 'pingxiang',
		),
		'py' => array(
			'en' => 'py',
			'cn' => '葡萄牙',
			'py' => 'putaoya',
		),
		'puyang' => array(
			'en' => 'pz',
			'cn' => '濮阳',
			'py' => 'puyang',
		),
		'pzh' => array(
			'en' => 'pzh',
			'cn' => '攀枝花',
			'py' => 'panzhihua',
		),
		'qianjiang' => array(
			'en' => 'qa',
			'cn' => '潜江',
			'py' => 'qianjiang',
		),
		'qiannan' => array(
			'en' => 'qb',
			'cn' => '黔南布依族苗族自治州',
			'py' => 'qiannan',
		),
		'qichun' => array(
			'en' => 'qc',
			'cn' => '蕲春',
			'py' => 'qichun',
		),
		'qd' => array(
			'en' => 'qd',
			'cn' => '青岛',
			'py' => 'qingdao',
		),
		'qingyang' => array(
			'en' => 'qg',
			'cn' => '庆阳',
			'py' => 'qingyang',
		),
		'qhd' => array(
			'en' => 'qhd',
			'cn' => '秦皇岛',
			'py' => 'qinhuangdao',
		),
		'qinzhou' => array(
			'en' => 'qinzhou',
			'cn' => '钦州',
			'py' => 'qinzhou',
		),
		'qujing' => array(
			'en' => 'qj',
			'cn' => '曲靖',
			'py' => 'qujing',
		),
		'qiann' => array(
			'en' => 'qn',
			'cn' => '黔南',
			'py' => 'qiannan',
		),
		'qidong' => array(
			'en' => 'qo',
			'cn' => '启东',
			'py' => 'qidong',
		),
		'qqhe' => array(
			'en' => 'qq',
			'cn' => '齐齐哈尔',
			'py' => 'qiqihaer',
		),
		'qth' => array(
			'en' => 'qt',
			'cn' => '七台河',
			'py' => 'qitaihe',
		),
		'quanzhou' => array(
			'en' => 'quanzhou',
			'cn' => '泉州',
			'py' => 'quanzhou',
		),
		'quzhou' => array(
			'en' => 'qw',
			'cn' => '衢州',
			'py' => 'quzhou',
		),
		'qianxn' => array(
			'en' => 'qx',
			'cn' => '黔西南',
			'py' => 'qianxinan',
		),
		'qingyuan' => array(
			'en' => 'qy',
			'cn' => '清远',
			'py' => 'qingyuan',
		),
		'rb' => array(
			'en' => 'rb',
			'cn' => '日本',
			'py' => 'riben',
		),
		'huairen' => array(
			'en' => 'rh',
			'cn' => '怀仁',
			'py' => 'huairen',
		),
		'ruijin' => array(
			'en' => 'rj',
			'cn' => '瑞金',
			'py' => 'ruijin',
		),
		'rikaze' => array(
			'en' => 'rk',
			'cn' => '日喀则',
			'py' => 'rikaze',
		),
		'ruzhou' => array(
			'en' => 'ru',
			'cn' => '汝州',
			'py' => 'ruzhou',
		),
		'rizhao' => array(
			'en' => 'rz',
			'cn' => '日照',
			'py' => 'rizhao',
		),
		'sanya' => array(
			'en' => 'sanya',
			'cn' => '三亚',
			'py' => 'sanya',
		),
		'shaoyang' => array(
			'en' => 'sb',
			'cn' => '邵阳',
			'py' => 'shaoyang',
		),
		'sc' => array(
			'en' => 'sc',
			'cn' => '四川',
			'py' => 'sichuan',
		),
		'sd' => array(
			'en' => 'sd',
			'cn' => '济南',
			'py' => 'jinan',
		),
		'shuozhou' => array(
			'en' => 'se',
			'cn' => '朔州',
			'py' => 'shuozhou',
		),
		'szs' => array(
			'en' => 'sf',
			'cn' => '石嘴山',
			'py' => 'shizuishan',
		),
		'shaoguan' => array(
			'en' => 'sg',
			'cn' => '韶关',
			'py' => 'shaoguan',
		),
		'sh' => array(
			'en' => 'sh',
			'cn' => '上海',
			'py' => 'shanghai',
		),
		'shantou' => array(
			'en' => 'shantou',
			'cn' => '汕头',
			'py' => 'shantou',
		),
		'shaoxing' => array(
			'en' => 'shaoxing',
			'cn' => '绍兴',
			'py' => 'shaoxing',
		),
		'shiyan' => array(
			'en' => 'si',
			'cn' => '十堰',
			'py' => 'shiyan',
		),
		'sjz' => array(
			'en' => 'sjz',
			'cn' => '石家庄',
			'py' => 'shijiazhuang',
		),
		'sys' => array(
			'en' => 'sk',
			'cn' => '双鸭山',
			'py' => 'shuangyashan',
		),
		'shannan' => array(
			'en' => 'sl',
			'cn' => '山南',
			'py' => 'shannan',
		),
		'shangqiu' => array(
			'en' => 'sm',
			'cn' => '商丘',
			'py' => 'shangqiu',
		),
		'siping' => array(
			'en' => 'sp',
			'cn' => '四平',
			'py' => 'siping',
		),
		'suqian' => array(
			'en' => 'sq',
			'cn' => '宿迁',
			'py' => 'suqian',
		),
		'shangrao' => array(
			'en' => 'sr',
			'cn' => '上饶',
			'py' => 'shangrao',
		),
		'jms' => array(
			'en' => 'ss',
			'cn' => '佳木斯',
			'py' => 'jiamusi',
		),
		'suining' => array(
			'en' => 'suining',
			'cn' => '遂宁',
			'py' => 'suining',
		),
		'suzhou' => array(
			'en' => 'suzhou',
			'cn' => '苏州',
			'py' => 'suzhou',
		),
		'suihua' => array(
			'en' => 'sv',
			'cn' => '绥化',
			'py' => 'suihua',
		),
		'shanwei' => array(
			'en' => 'sw',
			'cn' => '汕尾',
			'py' => 'shanwei',
		),
		'sx' => array(
			'en' => 'sx',
			'cn' => '西安',
			'py' => 'xian',
		),
		'sy' => array(
			'en' => 'sy',
			'cn' => '沈阳',
			'py' => 'shenyang',
		),
		'sz' => array(
			'en' => 'sz',
			'cn' => '深圳',
			'py' => 'shenzhen',
		),
		'taian' => array(
			'en' => 'taian',
			'cn' => '泰安',
			'py' => 'taian',
		),
		'taizhou' => array(
			'en' => 'taizhou',
			'cn' => '台州',
			'py' => 'taizhou',
		),
		'ts' => array(
			'en' => 'tangshan',
			'cn' => '唐山',
			'py' => 'tangshan',
		),
		'tz' => array(
			'en' => 'tb',
			'cn' => '泰州',
			'py' => 'taizhou',
		),
		'taicang' => array(
			'en' => 'tc',
			'cn' => '太仓',
			'py' => 'taicang',
		),
		'td' => array(
			'en' => 'td',
			'cn' => '泰国',
			'py' => 'taiguo',
		),
		'tongchuan' => array(
			'en' => 'te',
			'cn' => '铜川',
			'py' => 'tongchuan',
		),
		'tonghua' => array(
			'en' => 'th',
			'cn' => '通化',
			'py' => 'tonghua',
		),
		'tianshui' => array(
			'en' => 'ti',
			'cn' => '天水',
			'py' => 'tianshui',
		),
		'tj' => array(
			'en' => 'tj',
			'cn' => '天津',
			'py' => 'tianjin',
		),
		'tieling' => array(
			'en' => 'tl',
			'cn' => '铁岭',
			'py' => 'tieling',
		),
		'tianmen' => array(
			'en' => 'tm',
			'cn' => '天门',
			'py' => 'tianmen',
		),
		'tongliao' => array(
			'en' => 'tn',
			'cn' => '通辽',
			'py' => 'tongliao',
		),
		'tongling' => array(
			'en' => 'to',
			'cn' => '铜陵',
			'py' => 'tongling',
		),
		'tongren' => array(
			'en' => 'tr',
			'cn' => '铜仁',
			'py' => 'tongren',
		),
		'taixing' => array(
			'en' => 'tx',
			'cn' => '泰兴',
			'py' => 'taixing',
		),
		'shanxi' => array(
			'en' => 'ty',
			'cn' => '太原',
			'py' => 'taiyuan',
		),
		'huangnan' => array(
			'en' => 'ua',
			'cn' => '黄南',
			'py' => 'huangnan',
		),
		'yl' => array(
			'en' => 'ub',
			'cn' => '榆林',
			'py' => 'yulin',
		),
		'xuancheng' => array(
			'en' => 'uc',
			'cn' => '宣城',
			'py' => 'xuancheng',
		),
		'suizhong' => array(
			'en' => 'uh',
			'cn' => '绥中',
			'py' => 'suizhong',
		),
		'suizhou' => array(
			'en' => 'ui',
			'cn' => '随州',
			'py' => 'suizhou',
		),
		'wlcb' => array(
			'en' => 'ul',
			'cn' => '乌兰察布',
			'py' => 'wulanchabu',
		),
		'la' => array(
			'en' => 'un',
			'cn' => '六安',
			'py' => 'la',
		),
		'shangluo' => array(
			'en' => 'uo',
			'cn' => '商洛',
			'py' => 'shangluo',
		),
		'yushu' => array(
			'en' => 'ur',
			'cn' => '玉树',
			'py' => 'yushu',
		),
		'susong' => array(
			'en' => 'us',
			'cn' => '宿松',
			'py' => 'susong',
		),
		'hancheng' => array(
			'en' => 'uu',
			'cn' => '韩城',
			'py' => 'hancheng',
		),
		'szhou' => array(
			'en' => 'uz',
			'cn' => '宿州',
			'py' => 'suzhou',
		),
		'wuhai' => array(
			'en' => 'wa',
			'cn' => '乌海',
			'py' => 'wuhai',
		),
		'wuzhong' => array(
			'en' => 'wb',
			'cn' => '吴中',
			'py' => 'wuzhong',
		),
		'weifang' => array(
			'en' => 'weifang',
			'cn' => '潍坊',
			'py' => 'weifang',
		),
		'weihai' => array(
			'en' => 'weihai',
			'cn' => '威海',
			'py' => 'weihai',
		),
		'wh' => array(
			'en' => 'wh',
			'cn' => '武汉',
			'py' => 'wuhan',
		),
		'wujiang' => array(
			'en' => 'wj',
			'cn' => '吴江',
			'py' => 'wujiang',
		),
		'wlht' => array(
			'en' => 'wl',
			'cn' => '乌兰浩特',
			'py' => 'wulanhaote',
		),
		'weinan' => array(
			'en' => 'wn',
			'cn' => '渭南',
			'py' => 'weinan',
		),
		'wuzhou' => array(
			'en' => 'wo',
			'cn' => '梧州',
			'py' => 'wuzhou',
		),
		'wjq' => array(
			'en' => 'wq',
			'cn' => '五家渠',
			'py' => 'wujiaqu',
		),
		'wenshan' => array(
			'en' => 'ws',
			'cn' => '文山',
			'py' => 'wenshan',
		),
		'wuhu' => array(
			'en' => 'wu',
			'cn' => '芜湖',
			'py' => 'wuhu',
		),
		'wuwei' => array(
			'en' => 'ww',
			'cn' => '武威',
			'py' => 'wuwei',
		),
		'wx' => array(
			'en' => 'wx',
			'cn' => '无锡',
			'py' => 'wuxi',
		),
		'wenzhou' => array(
			'en' => 'wz',
			'cn' => '温州',
			'py' => 'wenzhou',
		),
		'xingtai' => array(
			'en' => 'xa',
			'cn' => '邢台',
			'py' => 'xingtai',
		),
		'xinyang' => array(
			'en' => 'xb',
			'cn' => '信阳',
			'py' => 'xinyang',
		),
		'xinzhou' => array(
			'en' => 'xc',
			'cn' => '忻州',
			'py' => 'xinzhou',
		),
		'xianning' => array(
			'en' => 'xd',
			'cn' => '咸宁',
			'py' => 'xianning',
		),
		'xam' => array(
			'en' => 'xe',
			'cn' => '兴安盟',
			'py' => 'xinganmeng',
		),
		'xiangfan' => array(
			'en' => 'xf',
			'cn' => '襄阳',
			'py' => 'xiangyang',
		),
		'xingyi' => array(
			'en' => 'xg',
			'cn' => '兴义',
			'py' => 'xingyi',
		),
		'xiaogan' => array(
			'en' => 'xh',
			'cn' => '孝感',
			'py' => 'xiaogan',
		),
		'lasa' => array(
			'en' => 'xi',
			'cn' => '西藏',
			'py' => 'xizang',
		),
		'xiangtan' => array(
			'en' => 'xiangtan',
			'cn' => '湘潭',
			'py' => 'xiangtan',
		),
		'xining' => array(
			'en' => 'xining',
			'cn' => '西宁',
			'py' => 'xining',
		),
		'wlmq' => array(
			'en' => 'xj',
			'cn' => '新疆',
			'py' => 'xinjiang',
		),
		'haixi' => array(
			'en' => 'xk',
			'cn' => '海西',
			'py' => 'haixi',
		),
		'xl' => array(
			'en' => 'xl',
			'cn' => '新西兰',
			'py' => 'xinxilan',
		),
		'xm' => array(
			'en' => 'xm',
			'cn' => '厦门',
			'py' => 'xiamen',
		),
		'xinyu' => array(
			'en' => 'xo',
			'cn' => '新余',
			'py' => 'xinyu',
		),
		'xp' => array(
			'en' => 'xp',
			'cn' => '新加坡',
			'py' => 'xinjiapo',
		),
		'xincai' => array(
			'en' => 'xq',
			'cn' => '新蔡',
			'py' => 'xincai',
		),
		'xsbn' => array(
			'en' => 'xs',
			'cn' => '西双版纳',
			'py' => 'xishuangbanna',
		),
		'xuchang' => array(
			'en' => 'xu',
			'cn' => '许昌',
			'py' => 'xuchang',
		),
		'xinxiang' => array(
			'en' => 'xx',
			'cn' => '新乡',
			'py' => 'xinxiang',
		),
		'xianyang' => array(
			'en' => 'xy',
			'cn' => '咸阳',
			'py' => 'xianyang',
		),
		'xz' => array(
			'en' => 'xz',
			'cn' => '徐州',
			'py' => 'xuzhou',
		),
		'yancheng' => array(
			'en' => 'ya',
			'cn' => '盐城',
			'py' => 'yancheng',
		),
		'yangzhou' => array(
			'en' => 'yd',
			'cn' => '扬州',
			'py' => 'yangzhou',
		),
		'yanji' => array(
			'en' => 'ye',
			'cn' => '延吉',
			'py' => 'yanji',
		),
		'yunfu' => array(
			'en' => 'yf',
			'cn' => '云浮',
			'py' => 'yunfu',
		),
		'lyg' => array(
			'en' => 'yg',
			'cn' => '连云港',
			'py' => 'lianyugang',
		),
		'yaan' => array(
			'en' => 'yh',
			'cn' => '雅安',
			'py' => 'yaan',
		),
		'yibin' => array(
			'en' => 'yibin',
			'cn' => '宜宾',
			'py' => 'yibin',
		),
		'yichang' => array(
			'en' => 'yichang',
			'cn' => '宜昌',
			'py' => 'yichang',
		),
		'yinchuan' => array(
			'en' => 'yinchuan',
			'cn' => '银川',
			'py' => 'yinchuan',
		),
		'yiyang' => array(
			'en' => 'yiyang',
			'cn' => '益阳',
			'py' => 'yiyang',
		),
		'yangjiang' => array(
			'en' => 'yj',
			'cn' => '阳江',
			'py' => 'yangjiang',
		),
		'yingkou' => array(
			'en' => 'yk',
			'cn' => '营口',
			'py' => 'yingkou',
		),
		'yulin' => array(
			'en' => 'yl',
			'cn' => '玉林',
			'py' => 'yulin',
		),
		'yichun' => array(
			'en' => 'ym',
			'cn' => '伊春',
			'py' => 'yichun',
		),
		'yn' => array(
			'en' => 'yn',
			'cn' => '昆明',
			'py' => 'kunming',
		),
		'yc' => array(
			'en' => 'yo',
			'cn' => '宜春',
			'py' => 'yichun',
		),
		'yongzhou' => array(
			'en' => 'yongzhou',
			'cn' => '永州',
			'py' => 'yongzhou',
		),
		'yanbian' => array(
			'en' => 'yp',
			'cn' => '延边',
			'py' => 'yanbian',
		),
		'yangquan' => array(
			'en' => 'yq',
			'cn' => '阳泉',
			'py' => 'yangquan',
		),
		'yingtan' => array(
			'en' => 'yr',
			'cn' => '鹰潭',
			'py' => 'yingtan',
		),
		'yuxi' => array(
			'en' => 'ys',
			'cn' => '玉溪',
			'py' => 'yuxi',
		),
		'yt' => array(
			'en' => 'yt',
			'cn' => '烟台',
			'py' => 'yantai',
		),
		'yuncheng' => array(
			'en' => 'yu',
			'cn' => '运城',
			'py' => 'yuncheng',
		),
		'yueyang' => array(
			'en' => 'yueyang',
			'cn' => '岳阳',
			'py' => 'yueyang',
		),
		'yiwu' => array(
			'en' => 'yw',
			'cn' => '义乌',
			'py' => 'yiwu',
		),
		'yx' => array(
			'en' => 'yx',
			'cn' => '宜兴',
			'py' => 'yixing',
		),
		'zb' => array(
			'en' => 'zb',
			'cn' => '淄博',
			'py' => 'zibo',
		),
		'zhanjiang' => array(
			'en' => 'zc',
			'cn' => '湛江',
			'py' => 'zhanjiang',
		),
		'zhenjiang' => array(
			'en' => 'zd',
			'cn' => '镇江',
			'py' => 'zhenjiang',
		),
		'zhoushan' => array(
			'en' => 'ze',
			'cn' => '舟山',
			'py' => 'zhoushan',
		),
		'zs' => array(
			'en' => 'zhongshan',
			'cn' => '中山',
			'py' => 'zhongshan',
		),
		'zh' => array(
			'en' => 'zhuhai',
			'cn' => '珠海',
			'py' => 'zhuhai',
		),
		'yanan' => array(
			'en' => 'zi',
			'cn' => '延安',
			'py' => 'yanan',
		),
		'zigong' => array(
			'en' => 'zigong',
			'cn' => '自贡',
			'py' => 'zigong',
		),
		'zjj' => array(
			'en' => 'zjj',
			'cn' => '张家界',
			'py' => 'zhangjiajie',
		),
		'zjk' => array(
			'en' => 'zjk',
			'cn' => '张家口',
			'py' => 'zhangjiakou',
		),
		'zhoukou' => array(
			'en' => 'zk',
			'cn' => '周口',
			'py' => 'zhoukou',
		),
		'gzl' => array(
			'en' => 'zl',
			'cn' => '公主岭',
			'py' => 'gongzhuling',
		),
		'zmd' => array(
			'en' => 'zm',
			'cn' => '驻马店',
			'py' => 'zhumadian',
		),
		'zhangye' => array(
			'en' => 'zn',
			'cn' => '张掖',
			'py' => 'zhangye',
		),
		'zhangzhou' => array(
			'en' => 'zo',
			'cn' => '漳州',
			'py' => 'zhangzhou',
		),
		'zhuji' => array(
			'en' => 'zp',
			'cn' => '诸暨',
			'py' => 'zhuji',
		),
		'zhaoqing' => array(
			'en' => 'zq',
			'cn' => '肇庆',
			'py' => 'zhaoqing',
		),
		'ziyang' => array(
			'en' => 'zr',
			'cn' => '资阳',
			'py' => 'ziyang',
		),
		'zhaotong' => array(
			'en' => 'zt',
			'cn' => '昭通',
			'py' => 'zhaotong',
		),
		'zaozhuang' => array(
			'en' => 'zu',
			'cn' => '枣庄',
			'py' => 'zaozhuang',
		),
		'zhongwei' => array(
			'en' => 'zw',
			'cn' => '中卫',
			'py' => 'zhongwei',
		),
		'zunyi' => array(
			'en' => 'zy',
			'cn' => '遵义',
			'py' => 'zunyi',
		),
		'zz' => array(
			'en' => 'zz',
			'cn' => '株洲',
			'py' => 'zhuzhou',
		),
	),
	// 直营站
	'DIRECT' => array(
		'bj' => array(
			'cn'=>'北京',
			'pub'=>'bj',
			'id'=>5894622582984222727
		),
		'beihai' => array(
			'cn'=>'北海',
			'pub'=>'beihai',
			'id'=>5894622627842304020
		),
		'nc' => array(
			'cn'=>'南昌',
			'pub'=>'nc',
			'id'=>5894622793924159568
		),
		'wuhu' => array(
			'cn'=>'芜湖',
			'pub'=>'wuhu',
			'id'=>5894622817248684120
		),
		'hf' => array(
			'cn'=>'合肥',
			'pub'=>'hf',
			'id'=>5894622820037896281
		),
		'guilin' => array(
			'cn'=>'桂林',
			'pub'=>'guilin',
			'id'=>5894622825628903515
		),
		'ks' => array(
			'cn'=>'昆山',
			'pub'=>'ks',
			'id'=>5894622831685478493
		),
		'tangshan' => array(
			'cn'=>'唐山',
			'pub'=>'tangshan',
			'id'=>5894622834474690654
		),
		'cq' => array(
			'cn'=>'重庆',
			'pub'=>'cq',
			'id'=>5894622840061503584
		),
		'wx' => array(
			'cn'=>'无锡',
			'pub'=>'wx',
			'id'=>5894622842863298657
		),
		'cz' => array(
			'cn'=>'常州',
			'pub'=>'cz',
			'id'=>5894622845681870946
		),
		'wlmq' => array(
			'cn'=>'乌鲁木齐',
			'pub'=>'wlmq',
			'id'=>5894622848487860323
		),
		'yt' => array(
			'cn'=>'烟台',
			'pub'=>'yt',
			'id'=>5894622854070478949
		),
		'weihai' => array(
			'cn'=>'威海',
			'pub'=>'weihai',
			'id'=>5894622856859691110
		),
		'shanxi' => array(
			'cn'=>'太原',
			'pub'=>'shanxi',
			'id'=>5894622859657291879
		),
		'zhongshan' => array(
			'cn'=>'中山',
			'pub'=>'zhongshan',
			'id'=>5894622876493228141
		),
		'gx' => array(
			'cn'=>'广西',
			'pub'=>'gx',
			'id'=>5894622910085408889
		),
		'zhuhai' => array(
			'cn'=>'珠海',
			'pub'=>'zhuhai',
			'id'=>5894622912883009658
		),
		'sx' => array(
			'cn'=>'陕西',
			'pub'=>'sx',
			'id'=>5894622915676416123
		),
		'nb' => array(
			'cn'=>'宁波',
			'pub'=>'nb',
			'id'=>5894622918482405500
		),
		'cs' => array(
			'cn'=>'长沙',
			'pub'=>'cs',
			'id'=>5894622921330337917
		),
		'sjz' => array(
			'cn'=>'石家庄',
			'pub'=>'sjz',
			'id'=>5894622924371208318
		),
		'sc' => array(
			'cn'=>'成都',
			'pub'=>'sc',
			'id'=>5894622927168809087
		),
		'sd' => array(
			'cn'=>'济南',
			'pub'=>'sd',
			'id'=>5894622944197683333
		),
		'nt' => array(
			'cn'=>'南通',
			'pub'=>'nt',
			'id'=>5894622947012061318
		),
		'hn' => array(
			'cn'=>'郑州',
			'pub'=>'hn',
			'id'=>5894622949797079175
		),
		'dl' => array(
			'cn'=>'大连',
			'pub'=>'dl',
			'id'=>5894622952590485640
		),
		'qd' => array(
			'cn'=>'青岛',
			'pub'=>'qd',
			'id'=>5894622955409057929
		),
		'sh' => array(
			'cn'=>'上海',
			'pub'=>'sh',
			'id'=>5894622958202464394
		),
		'tj' => array(
			'cn'=>'天津',
			'pub'=>'tj',
			'id'=>5894622961008453771
		),
		'sz' => array(
			'cn'=>'深圳',
			'pub'=>'sz',
			'id'=>5894622963806054540
		),
		'gz' => array(
			'cn'=>'广州',
			'pub'=>'gz',
			'id'=>5894622966603655309
		),
		'hz' => array(
			'cn'=>'杭州',
			'pub'=>'hz',
			'id'=>5894622969405450382
		),
		'wh' => array(
			'cn'=>'武汉',
			'pub'=>'wh',
			'id'=>5894622975000651920
		),
		'suzhou' => array(
			'cn'=>'苏州',
			'pub'=>'suzhou',
			'id'=>5894622977798252689
		),
		'nj' => array(
			'cn'=>'南京',
			'pub'=>'nj',
			'id'=>5894622980591659154
		),
		'fs' => array(
			'cn'=>'佛山',
			'pub'=>'fs',
			'id'=>5894623017350539423
		),
		'huizhou' => array(
			'cn'=>'惠州',
			'pub'=>'huizhou',
			'id'=>5894623020181694624
		),
		'dg' => array(
			'cn'=>'东莞',
			'pub'=>'dg',
			'id'=>5894623022996072609
		),
		'h' => array(
			'cn'=>'哈尔滨',
			'pub'=>'h',
			'id'=>5894623062548359343
		),
		'cc' => array(
			'cn'=>'长春',
			'pub'=>'cc',
			'id'=>5894623065597618352
		),
		'sy' => array(
			'cn'=>'沈阳',
			'pub'=>'sy',
			'id'=>5894623068630100145
		),
		'sanya' => array(
			'cn'=>'三亚',
			'pub'=>'sanya',
			'id'=>5894623071436089522
		),
		'boao' => array(
			'cn'=>'博鳌',
			'pub'=>'boao',
			'id'=>5894623074476959923
		),
		'han' => array(
			'cn'=>'海南',
			'pub'=>'han',
			'id'=>5894623077274560692
		),
		'kaifeng' => array(
			'cn'=>'开封',
			'pub'=>'kaifeng',
			'id'=>5894623080067967157
		),
		'jiangmen' => array(
			'cn'=>'江门',
			'pub'=>'jiangmen',
			'id'=>5894623088490129592
		),
		'zhaoqing' => array(
			'cn'=>'肇庆',
			'pub'=>'zhaoqing',
			'id'=>5894623091283536057
		),
		'huangshan' => array(
			'cn'=>'黄山',
			'pub'=>'huangshan',
			'id'=>5894623096899709115
		),
		'yn' => array(
			'cn'=>'云南',
			'pub'=>'yn',
			'id'=>5894623099718281404
		),
		'fushun' => array(
			'cn'=>'抚顺',
			'pub'=>'fushun',
			'id'=>5894623102520076477
		),
		'anshan' => array(
			'cn'=>'鞍山',
			'pub'=>'anshan',
			'id'=>5894623105321871550
		),
		'guizhou' => array(
			'cn'=>'贵阳',
			'pub'=>'guizhou',
			'id'=>5894623110959016128
		),
		'jiangyin' => array(
			'cn'=>'江阴',
			'pub'=>'jiangyin',
			'id'=>5894623125018323141
		),
		'qhd' => array(
			'cn'=>'秦皇岛',
			'pub'=>'qhd',
			'id'=>5894623131125229767
		),
		'baoding' => array(
			'cn'=>'保定',
			'pub'=>'baoding',
			'id'=>5894623136967895241
		),
		'hhht' => array(
			'cn'=>'呼和浩特',
			'pub'=>'hhht',
			'id'=>5894623165082314963
		),
		'bt' => array(
			'cn'=>'包头',
			'pub'=>'bt',
			'id'=>5894623167905081556
		),
		'xm' => array(
			'cn'=>'厦门',
			'pub'=>'xm',
			'id'=>5894623184950733018
		),
		'xz' => array(
			'cn'=>'徐州',
			'pub'=>'xz',
			'id'=>5894623193385478365
		),
		'yinchuan' => array(
			'cn'=>'银川',
			'pub'=>'yinchuan',
			'id'=>5894623252525164786
		),
		'lanzhou' => array(
			'cn'=>'兰州',
			'pub'=>'lanzhou',
			'id'=>5894623258137143540
		),
		'luoyang' => array(
			'cn'=>'洛阳',
			'pub'=>'luoyang',
			'id'=>5894623270061549816
		),
		'fj' => array(
			'cn'=>'福州',
			'pub'=>'fj',
			'id'=>5894623300495419650
		),
		'xianyang' => array(
			'cn'=>'咸阳',
			'pub'=>'xianyang',
			'id'=>5894623312675678471
		),
		'yangjiang' => array(
			'cn'=>'阳江',
			'pub'=>'yangjiang',
			'id'=>5894623579290806618
		),
		'macao' => array(
			'cn'=>'澳门',
			'pub'=>'macao',
			'id'=>5894623599515740512
		),
		'qingyuan' => array(
			'cn'=>'清远',
			'pub'=>'qingyuan',
			'id'=>5894623628791982441
		),
		'tieling' => array(
			'cn'=>'铁岭',
			'pub'=>'tieling',
			'id'=>5894623728238930312
		),
		'jinzhou' => array(
			'cn'=>'锦州',
			'pub'=>'jinzhou',
			'id'=>5894623734580717962
		),
	),
);